#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice.h>
#include <cydevice_trm.h>

/* Pin_Matrix_Switch_ISR_Time */
#define Pin_Matrix_Switch_ISR_Time__0__MASK 0x20u
#define Pin_Matrix_Switch_ISR_Time__0__PC CYREG_PRT1_PC5
#define Pin_Matrix_Switch_ISR_Time__0__PORT 1
#define Pin_Matrix_Switch_ISR_Time__0__SHIFT 5
#define Pin_Matrix_Switch_ISR_Time__AG CYREG_PRT1_AG
#define Pin_Matrix_Switch_ISR_Time__AMUX CYREG_PRT1_AMUX
#define Pin_Matrix_Switch_ISR_Time__BIE CYREG_PRT1_BIE
#define Pin_Matrix_Switch_ISR_Time__BIT_MASK CYREG_PRT1_BIT_MASK
#define Pin_Matrix_Switch_ISR_Time__BYP CYREG_PRT1_BYP
#define Pin_Matrix_Switch_ISR_Time__CTL CYREG_PRT1_CTL
#define Pin_Matrix_Switch_ISR_Time__DM0 CYREG_PRT1_DM0
#define Pin_Matrix_Switch_ISR_Time__DM1 CYREG_PRT1_DM1
#define Pin_Matrix_Switch_ISR_Time__DM2 CYREG_PRT1_DM2
#define Pin_Matrix_Switch_ISR_Time__DR CYREG_PRT1_DR
#define Pin_Matrix_Switch_ISR_Time__INP_DIS CYREG_PRT1_INP_DIS
#define Pin_Matrix_Switch_ISR_Time__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Pin_Matrix_Switch_ISR_Time__LCD_EN CYREG_PRT1_LCD_EN
#define Pin_Matrix_Switch_ISR_Time__MASK 0x20u
#define Pin_Matrix_Switch_ISR_Time__PORT 1
#define Pin_Matrix_Switch_ISR_Time__PRT CYREG_PRT1_PRT
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Pin_Matrix_Switch_ISR_Time__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Pin_Matrix_Switch_ISR_Time__PS CYREG_PRT1_PS
#define Pin_Matrix_Switch_ISR_Time__SHIFT 5
#define Pin_Matrix_Switch_ISR_Time__SLW CYREG_PRT1_SLW

/* Pin_Soft_Filter_Time */
#define Pin_Soft_Filter_Time__0__MASK 0x10u
#define Pin_Soft_Filter_Time__0__PC CYREG_PRT1_PC4
#define Pin_Soft_Filter_Time__0__PORT 1
#define Pin_Soft_Filter_Time__0__SHIFT 4
#define Pin_Soft_Filter_Time__AG CYREG_PRT1_AG
#define Pin_Soft_Filter_Time__AMUX CYREG_PRT1_AMUX
#define Pin_Soft_Filter_Time__BIE CYREG_PRT1_BIE
#define Pin_Soft_Filter_Time__BIT_MASK CYREG_PRT1_BIT_MASK
#define Pin_Soft_Filter_Time__BYP CYREG_PRT1_BYP
#define Pin_Soft_Filter_Time__CTL CYREG_PRT1_CTL
#define Pin_Soft_Filter_Time__DM0 CYREG_PRT1_DM0
#define Pin_Soft_Filter_Time__DM1 CYREG_PRT1_DM1
#define Pin_Soft_Filter_Time__DM2 CYREG_PRT1_DM2
#define Pin_Soft_Filter_Time__DR CYREG_PRT1_DR
#define Pin_Soft_Filter_Time__INP_DIS CYREG_PRT1_INP_DIS
#define Pin_Soft_Filter_Time__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Pin_Soft_Filter_Time__LCD_EN CYREG_PRT1_LCD_EN
#define Pin_Soft_Filter_Time__MASK 0x10u
#define Pin_Soft_Filter_Time__PORT 1
#define Pin_Soft_Filter_Time__PRT CYREG_PRT1_PRT
#define Pin_Soft_Filter_Time__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Pin_Soft_Filter_Time__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Pin_Soft_Filter_Time__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Pin_Soft_Filter_Time__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Pin_Soft_Filter_Time__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Pin_Soft_Filter_Time__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Pin_Soft_Filter_Time__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Pin_Soft_Filter_Time__PS CYREG_PRT1_PS
#define Pin_Soft_Filter_Time__SHIFT 4
#define Pin_Soft_Filter_Time__SLW CYREG_PRT1_SLW

/* VDAC8_Debug_viDAC8 */
#define VDAC8_Debug_viDAC8__CR0 CYREG_DAC3_CR0
#define VDAC8_Debug_viDAC8__CR1 CYREG_DAC3_CR1
#define VDAC8_Debug_viDAC8__D CYREG_DAC3_D
#define VDAC8_Debug_viDAC8__PM_ACT_CFG CYREG_PM_ACT_CFG8
#define VDAC8_Debug_viDAC8__PM_ACT_MSK 0x08u
#define VDAC8_Debug_viDAC8__PM_STBY_CFG CYREG_PM_STBY_CFG8
#define VDAC8_Debug_viDAC8__PM_STBY_MSK 0x08u
#define VDAC8_Debug_viDAC8__STROBE CYREG_DAC3_STROBE
#define VDAC8_Debug_viDAC8__SW0 CYREG_DAC3_SW0
#define VDAC8_Debug_viDAC8__SW2 CYREG_DAC3_SW2
#define VDAC8_Debug_viDAC8__SW3 CYREG_DAC3_SW3
#define VDAC8_Debug_viDAC8__SW4 CYREG_DAC3_SW4
#define VDAC8_Debug_viDAC8__TR CYREG_DAC3_TR
#define VDAC8_Debug_viDAC8__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DAC3_M1
#define VDAC8_Debug_viDAC8__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DAC3_M2
#define VDAC8_Debug_viDAC8__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DAC3_M3
#define VDAC8_Debug_viDAC8__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DAC3_M4
#define VDAC8_Debug_viDAC8__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DAC3_M5
#define VDAC8_Debug_viDAC8__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DAC3_M6
#define VDAC8_Debug_viDAC8__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DAC3_M7
#define VDAC8_Debug_viDAC8__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DAC3_M8
#define VDAC8_Debug_viDAC8__TRIM__TR CYREG_FLSHID_MFG_CFG_DAC3_TR
#define VDAC8_Debug_viDAC8__TST CYREG_DAC3_TST

/* ADC_SAR_A_ADC_SAR */
#define ADC_SAR_A_ADC_SAR__CLK CYREG_SAR0_CLK
#define ADC_SAR_A_ADC_SAR__CSR0 CYREG_SAR0_CSR0
#define ADC_SAR_A_ADC_SAR__CSR1 CYREG_SAR0_CSR1
#define ADC_SAR_A_ADC_SAR__CSR2 CYREG_SAR0_CSR2
#define ADC_SAR_A_ADC_SAR__CSR3 CYREG_SAR0_CSR3
#define ADC_SAR_A_ADC_SAR__CSR4 CYREG_SAR0_CSR4
#define ADC_SAR_A_ADC_SAR__CSR5 CYREG_SAR0_CSR5
#define ADC_SAR_A_ADC_SAR__CSR6 CYREG_SAR0_CSR6
#define ADC_SAR_A_ADC_SAR__CSR7 CYREG_SAR0_CSR7
#define ADC_SAR_A_ADC_SAR__PM_ACT_CFG CYREG_PM_ACT_CFG11
#define ADC_SAR_A_ADC_SAR__PM_ACT_MSK 0x01u
#define ADC_SAR_A_ADC_SAR__PM_STBY_CFG CYREG_PM_STBY_CFG11
#define ADC_SAR_A_ADC_SAR__PM_STBY_MSK 0x01u
#define ADC_SAR_A_ADC_SAR__SW0 CYREG_SAR0_SW0
#define ADC_SAR_A_ADC_SAR__SW2 CYREG_SAR0_SW2
#define ADC_SAR_A_ADC_SAR__SW3 CYREG_SAR0_SW3
#define ADC_SAR_A_ADC_SAR__SW4 CYREG_SAR0_SW4
#define ADC_SAR_A_ADC_SAR__SW6 CYREG_SAR0_SW6
#define ADC_SAR_A_ADC_SAR__TR0 CYREG_SAR0_TR0
#define ADC_SAR_A_ADC_SAR__TRIM__TR0 CYREG_FLSHID_MFG_CFG_SAR0_TR0
#define ADC_SAR_A_ADC_SAR__TRIM__TR1 CYREG_FLSHID_MFG_CFG_SAR0_TR1
#define ADC_SAR_A_ADC_SAR__WRK0 CYREG_SAR0_WRK0
#define ADC_SAR_A_ADC_SAR__WRK1 CYREG_SAR0_WRK1

/* ADC_SAR_A_theACLK */
#define ADC_SAR_A_theACLK__CFG0 CYREG_CLKDIST_DCFG1_CFG0
#define ADC_SAR_A_theACLK__CFG1 CYREG_CLKDIST_DCFG1_CFG1
#define ADC_SAR_A_theACLK__CFG2 CYREG_CLKDIST_DCFG1_CFG2
#define ADC_SAR_A_theACLK__CFG2_SRC_SEL_MASK 0x07u
#define ADC_SAR_A_theACLK__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define ADC_SAR_A_theACLK__PM_ACT_MSK 0x02u
#define ADC_SAR_A_theACLK__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define ADC_SAR_A_theACLK__PM_STBY_MSK 0x02u

/* ADC_SAR_B_ADC_SAR */
#define ADC_SAR_B_ADC_SAR__CLK CYREG_SAR1_CLK
#define ADC_SAR_B_ADC_SAR__CSR0 CYREG_SAR1_CSR0
#define ADC_SAR_B_ADC_SAR__CSR1 CYREG_SAR1_CSR1
#define ADC_SAR_B_ADC_SAR__CSR2 CYREG_SAR1_CSR2
#define ADC_SAR_B_ADC_SAR__CSR3 CYREG_SAR1_CSR3
#define ADC_SAR_B_ADC_SAR__CSR4 CYREG_SAR1_CSR4
#define ADC_SAR_B_ADC_SAR__CSR5 CYREG_SAR1_CSR5
#define ADC_SAR_B_ADC_SAR__CSR6 CYREG_SAR1_CSR6
#define ADC_SAR_B_ADC_SAR__CSR7 CYREG_SAR1_CSR7
#define ADC_SAR_B_ADC_SAR__PM_ACT_CFG CYREG_PM_ACT_CFG11
#define ADC_SAR_B_ADC_SAR__PM_ACT_MSK 0x02u
#define ADC_SAR_B_ADC_SAR__PM_STBY_CFG CYREG_PM_STBY_CFG11
#define ADC_SAR_B_ADC_SAR__PM_STBY_MSK 0x02u
#define ADC_SAR_B_ADC_SAR__SW0 CYREG_SAR1_SW0
#define ADC_SAR_B_ADC_SAR__SW2 CYREG_SAR1_SW2
#define ADC_SAR_B_ADC_SAR__SW3 CYREG_SAR1_SW3
#define ADC_SAR_B_ADC_SAR__SW4 CYREG_SAR1_SW4
#define ADC_SAR_B_ADC_SAR__SW6 CYREG_SAR1_SW6
#define ADC_SAR_B_ADC_SAR__TR0 CYREG_SAR1_TR0
#define ADC_SAR_B_ADC_SAR__TRIM__TR0 CYREG_FLSHID_MFG_CFG_SAR1_TR0
#define ADC_SAR_B_ADC_SAR__TRIM__TR1 CYREG_FLSHID_MFG_CFG_SAR1_TR1
#define ADC_SAR_B_ADC_SAR__WRK0 CYREG_SAR1_WRK0
#define ADC_SAR_B_ADC_SAR__WRK1 CYREG_SAR1_WRK1

/* ADC_SAR_B_theACLK */
#define ADC_SAR_B_theACLK__CFG0 CYREG_CLKDIST_DCFG0_CFG0
#define ADC_SAR_B_theACLK__CFG1 CYREG_CLKDIST_DCFG0_CFG1
#define ADC_SAR_B_theACLK__CFG2 CYREG_CLKDIST_DCFG0_CFG2
#define ADC_SAR_B_theACLK__CFG2_SRC_SEL_MASK 0x07u
#define ADC_SAR_B_theACLK__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define ADC_SAR_B_theACLK__PM_ACT_MSK 0x01u
#define ADC_SAR_B_theACLK__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define ADC_SAR_B_theACLK__PM_STBY_MSK 0x01u

/* USBUART_bus_reset */
#define USBUART_bus_reset__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_bus_reset__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_bus_reset__INTC_MASK 0x10000000u
#define USBUART_bus_reset__INTC_NUMBER 28
#define USBUART_bus_reset__INTC_PRIOR_NUM 7
#define USBUART_bus_reset__INTC_PRIOR_REG CYREG_NVIC_PRI_28
#define USBUART_bus_reset__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_bus_reset__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Clock_Signal_Out */
#define Clock_Signal_Out__CFG0 CYREG_CLKDIST_DCFG2_CFG0
#define Clock_Signal_Out__CFG1 CYREG_CLKDIST_DCFG2_CFG1
#define Clock_Signal_Out__CFG2 CYREG_CLKDIST_DCFG2_CFG2
#define Clock_Signal_Out__CFG2_SRC_SEL_MASK 0x07u
#define Clock_Signal_Out__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define Clock_Signal_Out__PM_ACT_MSK 0x04u
#define Clock_Signal_Out__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define Clock_Signal_Out__PM_STBY_MSK 0x04u

/* ISR_Debug_Fast_2 */
#define ISR_Debug_Fast_2__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ISR_Debug_Fast_2__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ISR_Debug_Fast_2__INTC_MASK 0x01u
#define ISR_Debug_Fast_2__INTC_NUMBER 0
#define ISR_Debug_Fast_2__INTC_PRIOR_NUM 7
#define ISR_Debug_Fast_2__INTC_PRIOR_REG CYREG_NVIC_PRI_0
#define ISR_Debug_Fast_2__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ISR_Debug_Fast_2__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Opamp_Debug_ABuf */
#define Opamp_Debug_ABuf__CR CYREG_ABUF3_CR
#define Opamp_Debug_ABuf__MX CYREG_ABUF3_MX
#define Opamp_Debug_ABuf__NPUMP_ABUF_TR0 CYREG_NPUMP_ABUF_TR0
#define Opamp_Debug_ABuf__PM_ACT_CFG CYREG_PM_ACT_CFG4
#define Opamp_Debug_ABuf__PM_ACT_MSK 0x08u
#define Opamp_Debug_ABuf__PM_STBY_CFG CYREG_PM_STBY_CFG4
#define Opamp_Debug_ABuf__PM_STBY_MSK 0x08u
#define Opamp_Debug_ABuf__RSVD CYREG_ABUF3_RSVD
#define Opamp_Debug_ABuf__SW CYREG_ABUF3_SW
#define Opamp_Debug_ABuf__TR0 CYREG_ABUF3_TR0
#define Opamp_Debug_ABuf__TR1 CYREG_ABUF3_TR1

/* Pin_Opamp_A_plus */
#define Pin_Opamp_A_plus__0__MASK 0x10u
#define Pin_Opamp_A_plus__0__PC CYREG_PRT0_PC4
#define Pin_Opamp_A_plus__0__PORT 0
#define Pin_Opamp_A_plus__0__SHIFT 4
#define Pin_Opamp_A_plus__AG CYREG_PRT0_AG
#define Pin_Opamp_A_plus__AMUX CYREG_PRT0_AMUX
#define Pin_Opamp_A_plus__BIE CYREG_PRT0_BIE
#define Pin_Opamp_A_plus__BIT_MASK CYREG_PRT0_BIT_MASK
#define Pin_Opamp_A_plus__BYP CYREG_PRT0_BYP
#define Pin_Opamp_A_plus__CTL CYREG_PRT0_CTL
#define Pin_Opamp_A_plus__DM0 CYREG_PRT0_DM0
#define Pin_Opamp_A_plus__DM1 CYREG_PRT0_DM1
#define Pin_Opamp_A_plus__DM2 CYREG_PRT0_DM2
#define Pin_Opamp_A_plus__DR CYREG_PRT0_DR
#define Pin_Opamp_A_plus__INP_DIS CYREG_PRT0_INP_DIS
#define Pin_Opamp_A_plus__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define Pin_Opamp_A_plus__LCD_EN CYREG_PRT0_LCD_EN
#define Pin_Opamp_A_plus__PORT 0
#define Pin_Opamp_A_plus__PRT CYREG_PRT0_PRT
#define Pin_Opamp_A_plus__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define Pin_Opamp_A_plus__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define Pin_Opamp_A_plus__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define Pin_Opamp_A_plus__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define Pin_Opamp_A_plus__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define Pin_Opamp_A_plus__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define Pin_Opamp_A_plus__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define Pin_Opamp_A_plus__PS CYREG_PRT0_PS
#define Pin_Opamp_A_plus__SLW CYREG_PRT0_SLW

/* Pin_Opamp_B_plus */
#define Pin_Opamp_B_plus__0__MASK 0x04u
#define Pin_Opamp_B_plus__0__PC CYREG_PRT0_PC2
#define Pin_Opamp_B_plus__0__PORT 0
#define Pin_Opamp_B_plus__0__SHIFT 2
#define Pin_Opamp_B_plus__AG CYREG_PRT0_AG
#define Pin_Opamp_B_plus__AMUX CYREG_PRT0_AMUX
#define Pin_Opamp_B_plus__BIE CYREG_PRT0_BIE
#define Pin_Opamp_B_plus__BIT_MASK CYREG_PRT0_BIT_MASK
#define Pin_Opamp_B_plus__BYP CYREG_PRT0_BYP
#define Pin_Opamp_B_plus__CTL CYREG_PRT0_CTL
#define Pin_Opamp_B_plus__DM0 CYREG_PRT0_DM0
#define Pin_Opamp_B_plus__DM1 CYREG_PRT0_DM1
#define Pin_Opamp_B_plus__DM2 CYREG_PRT0_DM2
#define Pin_Opamp_B_plus__DR CYREG_PRT0_DR
#define Pin_Opamp_B_plus__INP_DIS CYREG_PRT0_INP_DIS
#define Pin_Opamp_B_plus__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define Pin_Opamp_B_plus__LCD_EN CYREG_PRT0_LCD_EN
#define Pin_Opamp_B_plus__PORT 0
#define Pin_Opamp_B_plus__PRT CYREG_PRT0_PRT
#define Pin_Opamp_B_plus__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define Pin_Opamp_B_plus__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define Pin_Opamp_B_plus__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define Pin_Opamp_B_plus__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define Pin_Opamp_B_plus__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define Pin_Opamp_B_plus__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define Pin_Opamp_B_plus__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define Pin_Opamp_B_plus__PS CYREG_PRT0_PS
#define Pin_Opamp_B_plus__SLW CYREG_PRT0_SLW

/* Opamp_Vref_ABuf */
#define Opamp_Vref_ABuf__CR CYREG_ABUF1_CR
#define Opamp_Vref_ABuf__MX CYREG_ABUF1_MX
#define Opamp_Vref_ABuf__NPUMP_ABUF_TR0 CYREG_NPUMP_ABUF_TR0
#define Opamp_Vref_ABuf__PM_ACT_CFG CYREG_PM_ACT_CFG4
#define Opamp_Vref_ABuf__PM_ACT_MSK 0x02u
#define Opamp_Vref_ABuf__PM_STBY_CFG CYREG_PM_STBY_CFG4
#define Opamp_Vref_ABuf__PM_STBY_MSK 0x02u
#define Opamp_Vref_ABuf__RSVD CYREG_ABUF1_RSVD
#define Opamp_Vref_ABuf__SW CYREG_ABUF1_SW
#define Opamp_Vref_ABuf__TR0 CYREG_ABUF1_TR0
#define Opamp_Vref_ABuf__TR1 CYREG_ABUF1_TR1

/* PGA_Stage1_A_SC */
#define PGA_Stage1_A_SC__BST CYREG_SC2_BST
#define PGA_Stage1_A_SC__CLK CYREG_SC2_CLK
#define PGA_Stage1_A_SC__CR0 CYREG_SC2_CR0
#define PGA_Stage1_A_SC__CR1 CYREG_SC2_CR1
#define PGA_Stage1_A_SC__CR2 CYREG_SC2_CR2
#define PGA_Stage1_A_SC__MSK CYREG_SC_MSK
#define PGA_Stage1_A_SC__PM_ACT_CFG CYREG_PM_ACT_CFG9
#define PGA_Stage1_A_SC__PM_ACT_MSK 0x02u
#define PGA_Stage1_A_SC__PM_STBY_CFG CYREG_PM_STBY_CFG9
#define PGA_Stage1_A_SC__PM_STBY_MSK 0x02u
#define PGA_Stage1_A_SC__SR CYREG_SC_SR
#define PGA_Stage1_A_SC__SW0 CYREG_SC2_SW0
#define PGA_Stage1_A_SC__SW10 CYREG_SC2_SW10
#define PGA_Stage1_A_SC__SW2 CYREG_SC2_SW2
#define PGA_Stage1_A_SC__SW3 CYREG_SC2_SW3
#define PGA_Stage1_A_SC__SW4 CYREG_SC2_SW4
#define PGA_Stage1_A_SC__SW6 CYREG_SC2_SW6
#define PGA_Stage1_A_SC__SW7 CYREG_SC2_SW7
#define PGA_Stage1_A_SC__SW8 CYREG_SC2_SW8

/* PGA_Stage1_B_SC */
#define PGA_Stage1_B_SC__BST CYREG_SC1_BST
#define PGA_Stage1_B_SC__CLK CYREG_SC1_CLK
#define PGA_Stage1_B_SC__CR0 CYREG_SC1_CR0
#define PGA_Stage1_B_SC__CR1 CYREG_SC1_CR1
#define PGA_Stage1_B_SC__CR2 CYREG_SC1_CR2
#define PGA_Stage1_B_SC__MSK CYREG_SC_MSK
#define PGA_Stage1_B_SC__PM_ACT_CFG CYREG_PM_ACT_CFG9
#define PGA_Stage1_B_SC__PM_ACT_MSK 0x04u
#define PGA_Stage1_B_SC__PM_STBY_CFG CYREG_PM_STBY_CFG9
#define PGA_Stage1_B_SC__PM_STBY_MSK 0x04u
#define PGA_Stage1_B_SC__SR CYREG_SC_SR
#define PGA_Stage1_B_SC__SW0 CYREG_SC1_SW0
#define PGA_Stage1_B_SC__SW10 CYREG_SC1_SW10
#define PGA_Stage1_B_SC__SW2 CYREG_SC1_SW2
#define PGA_Stage1_B_SC__SW3 CYREG_SC1_SW3
#define PGA_Stage1_B_SC__SW4 CYREG_SC1_SW4
#define PGA_Stage1_B_SC__SW6 CYREG_SC1_SW6
#define PGA_Stage1_B_SC__SW7 CYREG_SC1_SW7
#define PGA_Stage1_B_SC__SW8 CYREG_SC1_SW8

/* PGA_Stage2_A_SC */
#define PGA_Stage2_A_SC__BST CYREG_SC0_BST
#define PGA_Stage2_A_SC__CLK CYREG_SC0_CLK
#define PGA_Stage2_A_SC__CR0 CYREG_SC0_CR0
#define PGA_Stage2_A_SC__CR1 CYREG_SC0_CR1
#define PGA_Stage2_A_SC__CR2 CYREG_SC0_CR2
#define PGA_Stage2_A_SC__MSK CYREG_SC_MSK
#define PGA_Stage2_A_SC__PM_ACT_CFG CYREG_PM_ACT_CFG9
#define PGA_Stage2_A_SC__PM_ACT_MSK 0x01u
#define PGA_Stage2_A_SC__PM_STBY_CFG CYREG_PM_STBY_CFG9
#define PGA_Stage2_A_SC__PM_STBY_MSK 0x01u
#define PGA_Stage2_A_SC__SR CYREG_SC_SR
#define PGA_Stage2_A_SC__SW0 CYREG_SC0_SW0
#define PGA_Stage2_A_SC__SW10 CYREG_SC0_SW10
#define PGA_Stage2_A_SC__SW2 CYREG_SC0_SW2
#define PGA_Stage2_A_SC__SW3 CYREG_SC0_SW3
#define PGA_Stage2_A_SC__SW4 CYREG_SC0_SW4
#define PGA_Stage2_A_SC__SW6 CYREG_SC0_SW6
#define PGA_Stage2_A_SC__SW7 CYREG_SC0_SW7
#define PGA_Stage2_A_SC__SW8 CYREG_SC0_SW8

/* PGA_Stage2_B_SC */
#define PGA_Stage2_B_SC__BST CYREG_SC3_BST
#define PGA_Stage2_B_SC__CLK CYREG_SC3_CLK
#define PGA_Stage2_B_SC__CR0 CYREG_SC3_CR0
#define PGA_Stage2_B_SC__CR1 CYREG_SC3_CR1
#define PGA_Stage2_B_SC__CR2 CYREG_SC3_CR2
#define PGA_Stage2_B_SC__MSK CYREG_SC_MSK
#define PGA_Stage2_B_SC__PM_ACT_CFG CYREG_PM_ACT_CFG9
#define PGA_Stage2_B_SC__PM_ACT_MSK 0x08u
#define PGA_Stage2_B_SC__PM_STBY_CFG CYREG_PM_STBY_CFG9
#define PGA_Stage2_B_SC__PM_STBY_MSK 0x08u
#define PGA_Stage2_B_SC__SR CYREG_SC_SR
#define PGA_Stage2_B_SC__SW0 CYREG_SC3_SW0
#define PGA_Stage2_B_SC__SW10 CYREG_SC3_SW10
#define PGA_Stage2_B_SC__SW2 CYREG_SC3_SW2
#define PGA_Stage2_B_SC__SW3 CYREG_SC3_SW3
#define PGA_Stage2_B_SC__SW4 CYREG_SC3_SW4
#define PGA_Stage2_B_SC__SW6 CYREG_SC3_SW6
#define PGA_Stage2_B_SC__SW7 CYREG_SC3_SW7
#define PGA_Stage2_B_SC__SW8 CYREG_SC3_SW8

/* Pin_Opamp_A_out */
#define Pin_Opamp_A_out__0__MASK 0x01u
#define Pin_Opamp_A_out__0__PC CYREG_PRT0_PC0
#define Pin_Opamp_A_out__0__PORT 0
#define Pin_Opamp_A_out__0__SHIFT 0
#define Pin_Opamp_A_out__AG CYREG_PRT0_AG
#define Pin_Opamp_A_out__AMUX CYREG_PRT0_AMUX
#define Pin_Opamp_A_out__BIE CYREG_PRT0_BIE
#define Pin_Opamp_A_out__BIT_MASK CYREG_PRT0_BIT_MASK
#define Pin_Opamp_A_out__BYP CYREG_PRT0_BYP
#define Pin_Opamp_A_out__CTL CYREG_PRT0_CTL
#define Pin_Opamp_A_out__DM0 CYREG_PRT0_DM0
#define Pin_Opamp_A_out__DM1 CYREG_PRT0_DM1
#define Pin_Opamp_A_out__DM2 CYREG_PRT0_DM2
#define Pin_Opamp_A_out__DR CYREG_PRT0_DR
#define Pin_Opamp_A_out__INP_DIS CYREG_PRT0_INP_DIS
#define Pin_Opamp_A_out__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define Pin_Opamp_A_out__LCD_EN CYREG_PRT0_LCD_EN
#define Pin_Opamp_A_out__PORT 0
#define Pin_Opamp_A_out__PRT CYREG_PRT0_PRT
#define Pin_Opamp_A_out__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define Pin_Opamp_A_out__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define Pin_Opamp_A_out__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define Pin_Opamp_A_out__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define Pin_Opamp_A_out__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define Pin_Opamp_A_out__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define Pin_Opamp_A_out__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define Pin_Opamp_A_out__PS CYREG_PRT0_PS
#define Pin_Opamp_A_out__SLW CYREG_PRT0_SLW

/* Pin_Opamp_B_out */
#define Pin_Opamp_B_out__0__MASK 0x02u
#define Pin_Opamp_B_out__0__PC CYREG_PRT0_PC1
#define Pin_Opamp_B_out__0__PORT 0
#define Pin_Opamp_B_out__0__SHIFT 1
#define Pin_Opamp_B_out__AG CYREG_PRT0_AG
#define Pin_Opamp_B_out__AMUX CYREG_PRT0_AMUX
#define Pin_Opamp_B_out__BIE CYREG_PRT0_BIE
#define Pin_Opamp_B_out__BIT_MASK CYREG_PRT0_BIT_MASK
#define Pin_Opamp_B_out__BYP CYREG_PRT0_BYP
#define Pin_Opamp_B_out__CTL CYREG_PRT0_CTL
#define Pin_Opamp_B_out__DM0 CYREG_PRT0_DM0
#define Pin_Opamp_B_out__DM1 CYREG_PRT0_DM1
#define Pin_Opamp_B_out__DM2 CYREG_PRT0_DM2
#define Pin_Opamp_B_out__DR CYREG_PRT0_DR
#define Pin_Opamp_B_out__INP_DIS CYREG_PRT0_INP_DIS
#define Pin_Opamp_B_out__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define Pin_Opamp_B_out__LCD_EN CYREG_PRT0_LCD_EN
#define Pin_Opamp_B_out__PORT 0
#define Pin_Opamp_B_out__PRT CYREG_PRT0_PRT
#define Pin_Opamp_B_out__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define Pin_Opamp_B_out__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define Pin_Opamp_B_out__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define Pin_Opamp_B_out__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define Pin_Opamp_B_out__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define Pin_Opamp_B_out__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define Pin_Opamp_B_out__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define Pin_Opamp_B_out__PS CYREG_PRT0_PS
#define Pin_Opamp_B_out__SLW CYREG_PRT0_SLW

/* Pin_Signal_In_A */
#define Pin_Signal_In_A__0__MASK 0x08u
#define Pin_Signal_In_A__0__PC CYREG_PRT0_PC3
#define Pin_Signal_In_A__0__PORT 0
#define Pin_Signal_In_A__0__SHIFT 3
#define Pin_Signal_In_A__AG CYREG_PRT0_AG
#define Pin_Signal_In_A__AMUX CYREG_PRT0_AMUX
#define Pin_Signal_In_A__BIE CYREG_PRT0_BIE
#define Pin_Signal_In_A__BIT_MASK CYREG_PRT0_BIT_MASK
#define Pin_Signal_In_A__BYP CYREG_PRT0_BYP
#define Pin_Signal_In_A__CTL CYREG_PRT0_CTL
#define Pin_Signal_In_A__DM0 CYREG_PRT0_DM0
#define Pin_Signal_In_A__DM1 CYREG_PRT0_DM1
#define Pin_Signal_In_A__DM2 CYREG_PRT0_DM2
#define Pin_Signal_In_A__DR CYREG_PRT0_DR
#define Pin_Signal_In_A__INP_DIS CYREG_PRT0_INP_DIS
#define Pin_Signal_In_A__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define Pin_Signal_In_A__LCD_EN CYREG_PRT0_LCD_EN
#define Pin_Signal_In_A__PORT 0
#define Pin_Signal_In_A__PRT CYREG_PRT0_PRT
#define Pin_Signal_In_A__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define Pin_Signal_In_A__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define Pin_Signal_In_A__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define Pin_Signal_In_A__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define Pin_Signal_In_A__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define Pin_Signal_In_A__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define Pin_Signal_In_A__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define Pin_Signal_In_A__PS CYREG_PRT0_PS
#define Pin_Signal_In_A__SLW CYREG_PRT0_SLW

/* Pin_Signal_In_B */
#define Pin_Signal_In_B__0__MASK 0x04u
#define Pin_Signal_In_B__0__PC CYREG_PRT1_PC2
#define Pin_Signal_In_B__0__PORT 1
#define Pin_Signal_In_B__0__SHIFT 2
#define Pin_Signal_In_B__AG CYREG_PRT1_AG
#define Pin_Signal_In_B__AMUX CYREG_PRT1_AMUX
#define Pin_Signal_In_B__BIE CYREG_PRT1_BIE
#define Pin_Signal_In_B__BIT_MASK CYREG_PRT1_BIT_MASK
#define Pin_Signal_In_B__BYP CYREG_PRT1_BYP
#define Pin_Signal_In_B__CTL CYREG_PRT1_CTL
#define Pin_Signal_In_B__DM0 CYREG_PRT1_DM0
#define Pin_Signal_In_B__DM1 CYREG_PRT1_DM1
#define Pin_Signal_In_B__DM2 CYREG_PRT1_DM2
#define Pin_Signal_In_B__DR CYREG_PRT1_DR
#define Pin_Signal_In_B__INP_DIS CYREG_PRT1_INP_DIS
#define Pin_Signal_In_B__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Pin_Signal_In_B__LCD_EN CYREG_PRT1_LCD_EN
#define Pin_Signal_In_B__PORT 1
#define Pin_Signal_In_B__PRT CYREG_PRT1_PRT
#define Pin_Signal_In_B__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Pin_Signal_In_B__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Pin_Signal_In_B__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Pin_Signal_In_B__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Pin_Signal_In_B__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Pin_Signal_In_B__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Pin_Signal_In_B__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Pin_Signal_In_B__PS CYREG_PRT1_PS
#define Pin_Signal_In_B__SLW CYREG_PRT1_SLW

/* USBUART_arb_int */
#define USBUART_arb_int__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_arb_int__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_arb_int__INTC_MASK 0x400000u
#define USBUART_arb_int__INTC_NUMBER 22
#define USBUART_arb_int__INTC_PRIOR_NUM 7
#define USBUART_arb_int__INTC_PRIOR_REG CYREG_NVIC_PRI_22
#define USBUART_arb_int__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_arb_int__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ord_int */
#define USBUART_ord_int__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ord_int__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ord_int__INTC_MASK 0x2000000u
#define USBUART_ord_int__INTC_NUMBER 25
#define USBUART_ord_int__INTC_PRIOR_NUM 7
#define USBUART_ord_int__INTC_PRIOR_REG CYREG_NVIC_PRI_25
#define USBUART_ord_int__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ord_int__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_sof_int */
#define USBUART_sof_int__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_sof_int__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_sof_int__INTC_MASK 0x800000u
#define USBUART_sof_int__INTC_NUMBER 23
#define USBUART_sof_int__INTC_PRIOR_NUM 7
#define USBUART_sof_int__INTC_PRIOR_REG CYREG_NVIC_PRI_23
#define USBUART_sof_int__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_sof_int__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* ISR_Debug_Fast */
#define ISR_Debug_Fast__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ISR_Debug_Fast__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ISR_Debug_Fast__INTC_MASK 0x1000u
#define ISR_Debug_Fast__INTC_NUMBER 12
#define ISR_Debug_Fast__INTC_PRIOR_NUM 7
#define ISR_Debug_Fast__INTC_PRIOR_REG CYREG_NVIC_PRI_12
#define ISR_Debug_Fast__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ISR_Debug_Fast__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* ISR_Debug_Slow */
#define ISR_Debug_Slow__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ISR_Debug_Slow__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ISR_Debug_Slow__INTC_MASK 0x200u
#define ISR_Debug_Slow__INTC_NUMBER 9
#define ISR_Debug_Slow__INTC_PRIOR_NUM 7
#define ISR_Debug_Slow__INTC_PRIOR_REG CYREG_NVIC_PRI_9
#define ISR_Debug_Slow__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ISR_Debug_Slow__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Matrix_Channel */
#define Matrix_Channel_ctrl_reg__0__MASK 0x01u
#define Matrix_Channel_ctrl_reg__0__POS 0
#define Matrix_Channel_ctrl_reg__1__MASK 0x02u
#define Matrix_Channel_ctrl_reg__1__POS 1
#define Matrix_Channel_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB07_08_ACTL
#define Matrix_Channel_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB07_08_CTL
#define Matrix_Channel_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB07_08_CTL
#define Matrix_Channel_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB07_08_CTL
#define Matrix_Channel_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB07_08_CTL
#define Matrix_Channel_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB07_08_MSK
#define Matrix_Channel_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB07_08_MSK
#define Matrix_Channel_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB07_08_MSK
#define Matrix_Channel_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB07_08_MSK
#define Matrix_Channel_ctrl_reg__2__MASK 0x04u
#define Matrix_Channel_ctrl_reg__2__POS 2
#define Matrix_Channel_ctrl_reg__3__MASK 0x08u
#define Matrix_Channel_ctrl_reg__3__POS 3
#define Matrix_Channel_ctrl_reg__4__MASK 0x10u
#define Matrix_Channel_ctrl_reg__4__POS 4
#define Matrix_Channel_ctrl_reg__5__MASK 0x20u
#define Matrix_Channel_ctrl_reg__5__POS 5
#define Matrix_Channel_ctrl_reg__6__MASK 0x40u
#define Matrix_Channel_ctrl_reg__6__POS 6
#define Matrix_Channel_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB07_ACTL
#define Matrix_Channel_ctrl_reg__CONTROL_REG CYREG_B0_UDB07_CTL
#define Matrix_Channel_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB07_ST_CTL
#define Matrix_Channel_ctrl_reg__COUNT_REG CYREG_B0_UDB07_CTL
#define Matrix_Channel_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB07_ST_CTL
#define Matrix_Channel_ctrl_reg__MASK 0x7Fu
#define Matrix_Channel_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB07_MSK_ACTL
#define Matrix_Channel_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB07_MSK_ACTL
#define Matrix_Channel_ctrl_reg__PERIOD_REG CYREG_B0_UDB07_MSK

/* VDAC8_0_viDAC8 */
#define VDAC8_0_viDAC8__CR0 CYREG_DAC0_CR0
#define VDAC8_0_viDAC8__CR1 CYREG_DAC0_CR1
#define VDAC8_0_viDAC8__D CYREG_DAC0_D
#define VDAC8_0_viDAC8__PM_ACT_CFG CYREG_PM_ACT_CFG8
#define VDAC8_0_viDAC8__PM_ACT_MSK 0x01u
#define VDAC8_0_viDAC8__PM_STBY_CFG CYREG_PM_STBY_CFG8
#define VDAC8_0_viDAC8__PM_STBY_MSK 0x01u
#define VDAC8_0_viDAC8__STROBE CYREG_DAC0_STROBE
#define VDAC8_0_viDAC8__SW0 CYREG_DAC0_SW0
#define VDAC8_0_viDAC8__SW2 CYREG_DAC0_SW2
#define VDAC8_0_viDAC8__SW3 CYREG_DAC0_SW3
#define VDAC8_0_viDAC8__SW4 CYREG_DAC0_SW4
#define VDAC8_0_viDAC8__TR CYREG_DAC0_TR
#define VDAC8_0_viDAC8__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DAC0_M1
#define VDAC8_0_viDAC8__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DAC0_M2
#define VDAC8_0_viDAC8__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DAC0_M3
#define VDAC8_0_viDAC8__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DAC0_M4
#define VDAC8_0_viDAC8__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DAC0_M5
#define VDAC8_0_viDAC8__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DAC0_M6
#define VDAC8_0_viDAC8__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DAC0_M7
#define VDAC8_0_viDAC8__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DAC0_M8
#define VDAC8_0_viDAC8__TRIM__TR CYREG_FLSHID_MFG_CFG_DAC0_TR
#define VDAC8_0_viDAC8__TST CYREG_DAC0_TST

/* ADC_SAR_A_IRQ */
#define ADC_SAR_A_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ADC_SAR_A_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ADC_SAR_A_IRQ__INTC_MASK 0x800u
#define ADC_SAR_A_IRQ__INTC_NUMBER 11
#define ADC_SAR_A_IRQ__INTC_PRIOR_NUM 7
#define ADC_SAR_A_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_11
#define ADC_SAR_A_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ADC_SAR_A_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* ADC_SAR_B_IRQ */
#define ADC_SAR_B_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ADC_SAR_B_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ADC_SAR_B_IRQ__INTC_MASK 0x10000u
#define ADC_SAR_B_IRQ__INTC_NUMBER 16
#define ADC_SAR_B_IRQ__INTC_PRIOR_NUM 7
#define ADC_SAR_B_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_16
#define ADC_SAR_B_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ADC_SAR_B_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Pin_Debug_IRQ */
#define Pin_Debug_IRQ__0__MASK 0x80u
#define Pin_Debug_IRQ__0__PC CYREG_PRT1_PC7
#define Pin_Debug_IRQ__0__PORT 1
#define Pin_Debug_IRQ__0__SHIFT 7
#define Pin_Debug_IRQ__AG CYREG_PRT1_AG
#define Pin_Debug_IRQ__AMUX CYREG_PRT1_AMUX
#define Pin_Debug_IRQ__BIE CYREG_PRT1_BIE
#define Pin_Debug_IRQ__BIT_MASK CYREG_PRT1_BIT_MASK
#define Pin_Debug_IRQ__BYP CYREG_PRT1_BYP
#define Pin_Debug_IRQ__CTL CYREG_PRT1_CTL
#define Pin_Debug_IRQ__DM0 CYREG_PRT1_DM0
#define Pin_Debug_IRQ__DM1 CYREG_PRT1_DM1
#define Pin_Debug_IRQ__DM2 CYREG_PRT1_DM2
#define Pin_Debug_IRQ__DR CYREG_PRT1_DR
#define Pin_Debug_IRQ__INP_DIS CYREG_PRT1_INP_DIS
#define Pin_Debug_IRQ__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Pin_Debug_IRQ__LCD_EN CYREG_PRT1_LCD_EN
#define Pin_Debug_IRQ__MASK 0x80u
#define Pin_Debug_IRQ__PORT 1
#define Pin_Debug_IRQ__PRT CYREG_PRT1_PRT
#define Pin_Debug_IRQ__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Pin_Debug_IRQ__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Pin_Debug_IRQ__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Pin_Debug_IRQ__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Pin_Debug_IRQ__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Pin_Debug_IRQ__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Pin_Debug_IRQ__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Pin_Debug_IRQ__PS CYREG_PRT1_PS
#define Pin_Debug_IRQ__SHIFT 7
#define Pin_Debug_IRQ__SLW CYREG_PRT1_SLW

/* DMA_Filter_A */
#define DMA_Filter_A__DRQ_CTL CYREG_IDMUX_DRQ_CTL2
#define DMA_Filter_A__DRQ_NUMBER 8
#define DMA_Filter_A__NUMBEROF_TDS 0
#define DMA_Filter_A__PRIORITY 2
#define DMA_Filter_A__TERMIN_EN 0
#define DMA_Filter_A__TERMIN_SEL 0
#define DMA_Filter_A__TERMOUT0_EN 0
#define DMA_Filter_A__TERMOUT0_SEL 0
#define DMA_Filter_A__TERMOUT1_EN 0
#define DMA_Filter_A__TERMOUT1_SEL 0

/* DMA_Filter_B */
#define DMA_Filter_B__DRQ_CTL CYREG_IDMUX_DRQ_CTL2
#define DMA_Filter_B__DRQ_NUMBER 9
#define DMA_Filter_B__NUMBEROF_TDS 0
#define DMA_Filter_B__PRIORITY 2
#define DMA_Filter_B__TERMIN_EN 0
#define DMA_Filter_B__TERMIN_SEL 0
#define DMA_Filter_B__TERMOUT0_EN 1
#define DMA_Filter_B__TERMOUT0_SEL 9
#define DMA_Filter_B__TERMOUT1_EN 1
#define DMA_Filter_B__TERMOUT1_SEL 10

/* Opamp_A_ABuf */
#define Opamp_A_ABuf__CR CYREG_ABUF2_CR
#define Opamp_A_ABuf__MX CYREG_ABUF2_MX
#define Opamp_A_ABuf__NPUMP_ABUF_TR0 CYREG_NPUMP_ABUF_TR0
#define Opamp_A_ABuf__PM_ACT_CFG CYREG_PM_ACT_CFG4
#define Opamp_A_ABuf__PM_ACT_MSK 0x04u
#define Opamp_A_ABuf__PM_STBY_CFG CYREG_PM_STBY_CFG4
#define Opamp_A_ABuf__PM_STBY_MSK 0x04u
#define Opamp_A_ABuf__RSVD CYREG_ABUF2_RSVD
#define Opamp_A_ABuf__SW CYREG_ABUF2_SW
#define Opamp_A_ABuf__TR0 CYREG_ABUF2_TR0
#define Opamp_A_ABuf__TR1 CYREG_ABUF2_TR1

/* Opamp_B_ABuf */
#define Opamp_B_ABuf__CR CYREG_ABUF0_CR
#define Opamp_B_ABuf__MX CYREG_ABUF0_MX
#define Opamp_B_ABuf__NPUMP_ABUF_TR0 CYREG_NPUMP_ABUF_TR0
#define Opamp_B_ABuf__PM_ACT_CFG CYREG_PM_ACT_CFG4
#define Opamp_B_ABuf__PM_ACT_MSK 0x01u
#define Opamp_B_ABuf__PM_STBY_CFG CYREG_PM_STBY_CFG4
#define Opamp_B_ABuf__PM_STBY_MSK 0x01u
#define Opamp_B_ABuf__RSVD CYREG_ABUF0_RSVD
#define Opamp_B_ABuf__SW CYREG_ABUF0_SW
#define Opamp_B_ABuf__TR0 CYREG_ABUF0_TR0
#define Opamp_B_ABuf__TR1 CYREG_ABUF0_TR1

/* Pin_Reserved */
#define Pin_Reserved__0__MASK 0x01u
#define Pin_Reserved__0__PC CYREG_PRT15_PC0
#define Pin_Reserved__0__PORT 15
#define Pin_Reserved__0__SHIFT 0
#define Pin_Reserved__1__MASK 0x02u
#define Pin_Reserved__1__PC CYREG_PRT15_PC1
#define Pin_Reserved__1__PORT 15
#define Pin_Reserved__1__SHIFT 1
#define Pin_Reserved__2__MASK 0x04u
#define Pin_Reserved__2__PC CYREG_PRT15_PC2
#define Pin_Reserved__2__PORT 15
#define Pin_Reserved__2__SHIFT 2
#define Pin_Reserved__3__MASK 0x08u
#define Pin_Reserved__3__PC CYREG_PRT15_PC3
#define Pin_Reserved__3__PORT 15
#define Pin_Reserved__3__SHIFT 3
#define Pin_Reserved__4__MASK 0x10u
#define Pin_Reserved__4__PC CYREG_PRT15_PC4
#define Pin_Reserved__4__PORT 15
#define Pin_Reserved__4__SHIFT 4
#define Pin_Reserved__5__MASK 0x20u
#define Pin_Reserved__5__PC CYREG_PRT15_PC5
#define Pin_Reserved__5__PORT 15
#define Pin_Reserved__5__SHIFT 5
#define Pin_Reserved__AG CYREG_PRT15_AG
#define Pin_Reserved__AMUX CYREG_PRT15_AMUX
#define Pin_Reserved__BIE CYREG_PRT15_BIE
#define Pin_Reserved__BIT_MASK CYREG_PRT15_BIT_MASK
#define Pin_Reserved__BYP CYREG_PRT15_BYP
#define Pin_Reserved__CTL CYREG_PRT15_CTL
#define Pin_Reserved__DM0 CYREG_PRT15_DM0
#define Pin_Reserved__DM1 CYREG_PRT15_DM1
#define Pin_Reserved__DM2 CYREG_PRT15_DM2
#define Pin_Reserved__DR CYREG_PRT15_DR
#define Pin_Reserved__INP_DIS CYREG_PRT15_INP_DIS
#define Pin_Reserved__LCD_COM_SEG CYREG_PRT15_LCD_COM_SEG
#define Pin_Reserved__LCD_EN CYREG_PRT15_LCD_EN
#define Pin_Reserved__PORT 15
#define Pin_Reserved__PRT CYREG_PRT15_PRT
#define Pin_Reserved__PRTDSI__CAPS_SEL CYREG_PRT15_CAPS_SEL
#define Pin_Reserved__PRTDSI__DBL_SYNC_IN CYREG_PRT15_DBL_SYNC_IN
#define Pin_Reserved__PRTDSI__OE_SEL0 CYREG_PRT15_OE_SEL0
#define Pin_Reserved__PRTDSI__OE_SEL1 CYREG_PRT15_OE_SEL1
#define Pin_Reserved__PRTDSI__OUT_SEL0 CYREG_PRT15_OUT_SEL0
#define Pin_Reserved__PRTDSI__OUT_SEL1 CYREG_PRT15_OUT_SEL1
#define Pin_Reserved__PRTDSI__SYNC_OUT CYREG_PRT15_SYNC_OUT
#define Pin_Reserved__PS CYREG_PRT15_PS
#define Pin_Reserved__SLW CYREG_PRT15_SLW

/* Pin_Row_IO_A */
#define Pin_Row_IO_A__0__MASK 0x40u
#define Pin_Row_IO_A__0__PC CYREG_PRT0_PC6
#define Pin_Row_IO_A__0__PORT 0
#define Pin_Row_IO_A__0__SHIFT 6
#define Pin_Row_IO_A__AG CYREG_PRT0_AG
#define Pin_Row_IO_A__AMUX CYREG_PRT0_AMUX
#define Pin_Row_IO_A__BIE CYREG_PRT0_BIE
#define Pin_Row_IO_A__BIT_MASK CYREG_PRT0_BIT_MASK
#define Pin_Row_IO_A__BYP CYREG_PRT0_BYP
#define Pin_Row_IO_A__CTL CYREG_PRT0_CTL
#define Pin_Row_IO_A__DM0 CYREG_PRT0_DM0
#define Pin_Row_IO_A__DM1 CYREG_PRT0_DM1
#define Pin_Row_IO_A__DM2 CYREG_PRT0_DM2
#define Pin_Row_IO_A__DR CYREG_PRT0_DR
#define Pin_Row_IO_A__INP_DIS CYREG_PRT0_INP_DIS
#define Pin_Row_IO_A__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define Pin_Row_IO_A__LCD_EN CYREG_PRT0_LCD_EN
#define Pin_Row_IO_A__PORT 0
#define Pin_Row_IO_A__PRT CYREG_PRT0_PRT
#define Pin_Row_IO_A__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define Pin_Row_IO_A__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define Pin_Row_IO_A__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define Pin_Row_IO_A__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define Pin_Row_IO_A__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define Pin_Row_IO_A__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define Pin_Row_IO_A__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define Pin_Row_IO_A__PS CYREG_PRT0_PS
#define Pin_Row_IO_A__SLW CYREG_PRT0_SLW

/* Pin_Row_IO_B */
#define Pin_Row_IO_B__0__MASK 0x40u
#define Pin_Row_IO_B__0__PC CYREG_PRT1_PC6
#define Pin_Row_IO_B__0__PORT 1
#define Pin_Row_IO_B__0__SHIFT 6
#define Pin_Row_IO_B__AG CYREG_PRT1_AG
#define Pin_Row_IO_B__AMUX CYREG_PRT1_AMUX
#define Pin_Row_IO_B__BIE CYREG_PRT1_BIE
#define Pin_Row_IO_B__BIT_MASK CYREG_PRT1_BIT_MASK
#define Pin_Row_IO_B__BYP CYREG_PRT1_BYP
#define Pin_Row_IO_B__CTL CYREG_PRT1_CTL
#define Pin_Row_IO_B__DM0 CYREG_PRT1_DM0
#define Pin_Row_IO_B__DM1 CYREG_PRT1_DM1
#define Pin_Row_IO_B__DM2 CYREG_PRT1_DM2
#define Pin_Row_IO_B__DR CYREG_PRT1_DR
#define Pin_Row_IO_B__INP_DIS CYREG_PRT1_INP_DIS
#define Pin_Row_IO_B__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define Pin_Row_IO_B__LCD_EN CYREG_PRT1_LCD_EN
#define Pin_Row_IO_B__PORT 1
#define Pin_Row_IO_B__PRT CYREG_PRT1_PRT
#define Pin_Row_IO_B__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define Pin_Row_IO_B__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define Pin_Row_IO_B__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define Pin_Row_IO_B__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define Pin_Row_IO_B__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define Pin_Row_IO_B__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define Pin_Row_IO_B__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define Pin_Row_IO_B__PS CYREG_PRT1_PS
#define Pin_Row_IO_B__SLW CYREG_PRT1_SLW

/* USBUART_ep_0 */
#define USBUART_ep_0__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_0__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_0__INTC_MASK 0x4000000u
#define USBUART_ep_0__INTC_NUMBER 26
#define USBUART_ep_0__INTC_PRIOR_NUM 7
#define USBUART_ep_0__INTC_PRIOR_REG CYREG_NVIC_PRI_26
#define USBUART_ep_0__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_0__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_1 */
#define USBUART_ep_1__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_1__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_1__INTC_MASK 0x20000000u
#define USBUART_ep_1__INTC_NUMBER 29
#define USBUART_ep_1__INTC_PRIOR_NUM 7
#define USBUART_ep_1__INTC_PRIOR_REG CYREG_NVIC_PRI_29
#define USBUART_ep_1__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_1__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_2 */
#define USBUART_ep_2__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_2__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_2__INTC_MASK 0x80000000u
#define USBUART_ep_2__INTC_NUMBER 31
#define USBUART_ep_2__INTC_PRIOR_NUM 7
#define USBUART_ep_2__INTC_PRIOR_REG CYREG_NVIC_PRI_31
#define USBUART_ep_2__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_2__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_3 */
#define USBUART_ep_3__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_3__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_3__INTC_MASK 0x8000000u
#define USBUART_ep_3__INTC_NUMBER 27
#define USBUART_ep_3__INTC_PRIOR_NUM 7
#define USBUART_ep_3__INTC_PRIOR_REG CYREG_NVIC_PRI_27
#define USBUART_ep_3__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_3__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_4 */
#define USBUART_ep_4__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_4__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_4__INTC_MASK 0x04u
#define USBUART_ep_4__INTC_NUMBER 2
#define USBUART_ep_4__INTC_PRIOR_NUM 7
#define USBUART_ep_4__INTC_PRIOR_REG CYREG_NVIC_PRI_2
#define USBUART_ep_4__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_4__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_5 */
#define USBUART_ep_5__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_5__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_5__INTC_MASK 0x08u
#define USBUART_ep_5__INTC_NUMBER 3
#define USBUART_ep_5__INTC_PRIOR_NUM 7
#define USBUART_ep_5__INTC_PRIOR_REG CYREG_NVIC_PRI_3
#define USBUART_ep_5__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_5__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_6 */
#define USBUART_ep_6__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_6__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_6__INTC_MASK 0x80000u
#define USBUART_ep_6__INTC_NUMBER 19
#define USBUART_ep_6__INTC_PRIOR_NUM 7
#define USBUART_ep_6__INTC_PRIOR_REG CYREG_NVIC_PRI_19
#define USBUART_ep_6__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_6__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_7 */
#define USBUART_ep_7__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_7__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_7__INTC_MASK 0x1000000u
#define USBUART_ep_7__INTC_NUMBER 24
#define USBUART_ep_7__INTC_PRIOR_NUM 7
#define USBUART_ep_7__INTC_PRIOR_REG CYREG_NVIC_PRI_24
#define USBUART_ep_7__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_7__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_ep_8 */
#define USBUART_ep_8__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define USBUART_ep_8__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define USBUART_ep_8__INTC_MASK 0x200000u
#define USBUART_ep_8__INTC_NUMBER 21
#define USBUART_ep_8__INTC_PRIOR_NUM 7
#define USBUART_ep_8__INTC_PRIOR_REG CYREG_NVIC_PRI_21
#define USBUART_ep_8__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define USBUART_ep_8__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* LCD_LCDPort */
#define LCD_LCDPort__0__MASK 0x01u
#define LCD_LCDPort__0__PC CYREG_PRT2_PC0
#define LCD_LCDPort__0__PORT 2
#define LCD_LCDPort__0__SHIFT 0
#define LCD_LCDPort__1__MASK 0x02u
#define LCD_LCDPort__1__PC CYREG_PRT2_PC1
#define LCD_LCDPort__1__PORT 2
#define LCD_LCDPort__1__SHIFT 1
#define LCD_LCDPort__2__MASK 0x04u
#define LCD_LCDPort__2__PC CYREG_PRT2_PC2
#define LCD_LCDPort__2__PORT 2
#define LCD_LCDPort__2__SHIFT 2
#define LCD_LCDPort__3__MASK 0x08u
#define LCD_LCDPort__3__PC CYREG_PRT2_PC3
#define LCD_LCDPort__3__PORT 2
#define LCD_LCDPort__3__SHIFT 3
#define LCD_LCDPort__4__MASK 0x10u
#define LCD_LCDPort__4__PC CYREG_PRT2_PC4
#define LCD_LCDPort__4__PORT 2
#define LCD_LCDPort__4__SHIFT 4
#define LCD_LCDPort__5__MASK 0x20u
#define LCD_LCDPort__5__PC CYREG_PRT2_PC5
#define LCD_LCDPort__5__PORT 2
#define LCD_LCDPort__5__SHIFT 5
#define LCD_LCDPort__6__MASK 0x40u
#define LCD_LCDPort__6__PC CYREG_PRT2_PC6
#define LCD_LCDPort__6__PORT 2
#define LCD_LCDPort__6__SHIFT 6
#define LCD_LCDPort__AG CYREG_PRT2_AG
#define LCD_LCDPort__AMUX CYREG_PRT2_AMUX
#define LCD_LCDPort__BIE CYREG_PRT2_BIE
#define LCD_LCDPort__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_LCDPort__BYP CYREG_PRT2_BYP
#define LCD_LCDPort__CTL CYREG_PRT2_CTL
#define LCD_LCDPort__DM0 CYREG_PRT2_DM0
#define LCD_LCDPort__DM1 CYREG_PRT2_DM1
#define LCD_LCDPort__DM2 CYREG_PRT2_DM2
#define LCD_LCDPort__DR CYREG_PRT2_DR
#define LCD_LCDPort__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_LCDPort__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_LCDPort__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_LCDPort__MASK 0x7Fu
#define LCD_LCDPort__PORT 2
#define LCD_LCDPort__PRT CYREG_PRT2_PRT
#define LCD_LCDPort__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_LCDPort__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_LCDPort__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_LCDPort__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_LCDPort__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_LCDPort__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_LCDPort__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_LCDPort__PS CYREG_PRT2_PS
#define LCD_LCDPort__SHIFT 0
#define LCD_LCDPort__SLW CYREG_PRT2_SLW

/* USBUART_USB */
#define USBUART_USB__ARB_CFG CYREG_USB_ARB_CFG
#define USBUART_USB__ARB_EP1_CFG CYREG_USB_ARB_EP1_CFG
#define USBUART_USB__ARB_EP1_INT_EN CYREG_USB_ARB_EP1_INT_EN
#define USBUART_USB__ARB_EP1_SR CYREG_USB_ARB_EP1_SR
#define USBUART_USB__ARB_EP2_CFG CYREG_USB_ARB_EP2_CFG
#define USBUART_USB__ARB_EP2_INT_EN CYREG_USB_ARB_EP2_INT_EN
#define USBUART_USB__ARB_EP2_SR CYREG_USB_ARB_EP2_SR
#define USBUART_USB__ARB_EP3_CFG CYREG_USB_ARB_EP3_CFG
#define USBUART_USB__ARB_EP3_INT_EN CYREG_USB_ARB_EP3_INT_EN
#define USBUART_USB__ARB_EP3_SR CYREG_USB_ARB_EP3_SR
#define USBUART_USB__ARB_EP4_CFG CYREG_USB_ARB_EP4_CFG
#define USBUART_USB__ARB_EP4_INT_EN CYREG_USB_ARB_EP4_INT_EN
#define USBUART_USB__ARB_EP4_SR CYREG_USB_ARB_EP4_SR
#define USBUART_USB__ARB_EP5_CFG CYREG_USB_ARB_EP5_CFG
#define USBUART_USB__ARB_EP5_INT_EN CYREG_USB_ARB_EP5_INT_EN
#define USBUART_USB__ARB_EP5_SR CYREG_USB_ARB_EP5_SR
#define USBUART_USB__ARB_EP6_CFG CYREG_USB_ARB_EP6_CFG
#define USBUART_USB__ARB_EP6_INT_EN CYREG_USB_ARB_EP6_INT_EN
#define USBUART_USB__ARB_EP6_SR CYREG_USB_ARB_EP6_SR
#define USBUART_USB__ARB_EP7_CFG CYREG_USB_ARB_EP7_CFG
#define USBUART_USB__ARB_EP7_INT_EN CYREG_USB_ARB_EP7_INT_EN
#define USBUART_USB__ARB_EP7_SR CYREG_USB_ARB_EP7_SR
#define USBUART_USB__ARB_EP8_CFG CYREG_USB_ARB_EP8_CFG
#define USBUART_USB__ARB_EP8_INT_EN CYREG_USB_ARB_EP8_INT_EN
#define USBUART_USB__ARB_EP8_SR CYREG_USB_ARB_EP8_SR
#define USBUART_USB__ARB_INT_EN CYREG_USB_ARB_INT_EN
#define USBUART_USB__ARB_INT_SR CYREG_USB_ARB_INT_SR
#define USBUART_USB__ARB_RW1_DR CYREG_USB_ARB_RW1_DR
#define USBUART_USB__ARB_RW1_RA CYREG_USB_ARB_RW1_RA
#define USBUART_USB__ARB_RW1_RA_MSB CYREG_USB_ARB_RW1_RA_MSB
#define USBUART_USB__ARB_RW1_WA CYREG_USB_ARB_RW1_WA
#define USBUART_USB__ARB_RW1_WA_MSB CYREG_USB_ARB_RW1_WA_MSB
#define USBUART_USB__ARB_RW2_DR CYREG_USB_ARB_RW2_DR
#define USBUART_USB__ARB_RW2_RA CYREG_USB_ARB_RW2_RA
#define USBUART_USB__ARB_RW2_RA_MSB CYREG_USB_ARB_RW2_RA_MSB
#define USBUART_USB__ARB_RW2_WA CYREG_USB_ARB_RW2_WA
#define USBUART_USB__ARB_RW2_WA_MSB CYREG_USB_ARB_RW2_WA_MSB
#define USBUART_USB__ARB_RW3_DR CYREG_USB_ARB_RW3_DR
#define USBUART_USB__ARB_RW3_RA CYREG_USB_ARB_RW3_RA
#define USBUART_USB__ARB_RW3_RA_MSB CYREG_USB_ARB_RW3_RA_MSB
#define USBUART_USB__ARB_RW3_WA CYREG_USB_ARB_RW3_WA
#define USBUART_USB__ARB_RW3_WA_MSB CYREG_USB_ARB_RW3_WA_MSB
#define USBUART_USB__ARB_RW4_DR CYREG_USB_ARB_RW4_DR
#define USBUART_USB__ARB_RW4_RA CYREG_USB_ARB_RW4_RA
#define USBUART_USB__ARB_RW4_RA_MSB CYREG_USB_ARB_RW4_RA_MSB
#define USBUART_USB__ARB_RW4_WA CYREG_USB_ARB_RW4_WA
#define USBUART_USB__ARB_RW4_WA_MSB CYREG_USB_ARB_RW4_WA_MSB
#define USBUART_USB__ARB_RW5_DR CYREG_USB_ARB_RW5_DR
#define USBUART_USB__ARB_RW5_RA CYREG_USB_ARB_RW5_RA
#define USBUART_USB__ARB_RW5_RA_MSB CYREG_USB_ARB_RW5_RA_MSB
#define USBUART_USB__ARB_RW5_WA CYREG_USB_ARB_RW5_WA
#define USBUART_USB__ARB_RW5_WA_MSB CYREG_USB_ARB_RW5_WA_MSB
#define USBUART_USB__ARB_RW6_DR CYREG_USB_ARB_RW6_DR
#define USBUART_USB__ARB_RW6_RA CYREG_USB_ARB_RW6_RA
#define USBUART_USB__ARB_RW6_RA_MSB CYREG_USB_ARB_RW6_RA_MSB
#define USBUART_USB__ARB_RW6_WA CYREG_USB_ARB_RW6_WA
#define USBUART_USB__ARB_RW6_WA_MSB CYREG_USB_ARB_RW6_WA_MSB
#define USBUART_USB__ARB_RW7_DR CYREG_USB_ARB_RW7_DR
#define USBUART_USB__ARB_RW7_RA CYREG_USB_ARB_RW7_RA
#define USBUART_USB__ARB_RW7_RA_MSB CYREG_USB_ARB_RW7_RA_MSB
#define USBUART_USB__ARB_RW7_WA CYREG_USB_ARB_RW7_WA
#define USBUART_USB__ARB_RW7_WA_MSB CYREG_USB_ARB_RW7_WA_MSB
#define USBUART_USB__ARB_RW8_DR CYREG_USB_ARB_RW8_DR
#define USBUART_USB__ARB_RW8_RA CYREG_USB_ARB_RW8_RA
#define USBUART_USB__ARB_RW8_RA_MSB CYREG_USB_ARB_RW8_RA_MSB
#define USBUART_USB__ARB_RW8_WA CYREG_USB_ARB_RW8_WA
#define USBUART_USB__ARB_RW8_WA_MSB CYREG_USB_ARB_RW8_WA_MSB
#define USBUART_USB__BUF_SIZE CYREG_USB_BUF_SIZE
#define USBUART_USB__BUS_RST_CNT CYREG_USB_BUS_RST_CNT
#define USBUART_USB__CR0 CYREG_USB_CR0
#define USBUART_USB__CR1 CYREG_USB_CR1
#define USBUART_USB__CWA CYREG_USB_CWA
#define USBUART_USB__CWA_MSB CYREG_USB_CWA_MSB
#define USBUART_USB__DMA_THRES CYREG_USB_DMA_THRES
#define USBUART_USB__DMA_THRES_MSB CYREG_USB_DMA_THRES_MSB
#define USBUART_USB__EP_ACTIVE CYREG_USB_EP_ACTIVE
#define USBUART_USB__EP_TYPE CYREG_USB_EP_TYPE
#define USBUART_USB__EP0_CNT CYREG_USB_EP0_CNT
#define USBUART_USB__EP0_CR CYREG_USB_EP0_CR
#define USBUART_USB__EP0_DR0 CYREG_USB_EP0_DR0
#define USBUART_USB__EP0_DR1 CYREG_USB_EP0_DR1
#define USBUART_USB__EP0_DR2 CYREG_USB_EP0_DR2
#define USBUART_USB__EP0_DR3 CYREG_USB_EP0_DR3
#define USBUART_USB__EP0_DR4 CYREG_USB_EP0_DR4
#define USBUART_USB__EP0_DR5 CYREG_USB_EP0_DR5
#define USBUART_USB__EP0_DR6 CYREG_USB_EP0_DR6
#define USBUART_USB__EP0_DR7 CYREG_USB_EP0_DR7
#define USBUART_USB__MEM_DATA CYREG_USB_MEM_DATA_MBASE
#define USBUART_USB__OSCLK_DR0 CYREG_USB_OSCLK_DR0
#define USBUART_USB__OSCLK_DR1 CYREG_USB_OSCLK_DR1
#define USBUART_USB__PM_ACT_CFG CYREG_PM_ACT_CFG5
#define USBUART_USB__PM_ACT_MSK 0x01u
#define USBUART_USB__PM_STBY_CFG CYREG_PM_STBY_CFG5
#define USBUART_USB__PM_STBY_MSK 0x01u
#define USBUART_USB__SIE_EP_INT_EN CYREG_USB_SIE_EP_INT_EN
#define USBUART_USB__SIE_EP_INT_SR CYREG_USB_SIE_EP_INT_SR
#define USBUART_USB__SIE_EP1_CNT0 CYREG_USB_SIE_EP1_CNT0
#define USBUART_USB__SIE_EP1_CNT1 CYREG_USB_SIE_EP1_CNT1
#define USBUART_USB__SIE_EP1_CR0 CYREG_USB_SIE_EP1_CR0
#define USBUART_USB__SIE_EP2_CNT0 CYREG_USB_SIE_EP2_CNT0
#define USBUART_USB__SIE_EP2_CNT1 CYREG_USB_SIE_EP2_CNT1
#define USBUART_USB__SIE_EP2_CR0 CYREG_USB_SIE_EP2_CR0
#define USBUART_USB__SIE_EP3_CNT0 CYREG_USB_SIE_EP3_CNT0
#define USBUART_USB__SIE_EP3_CNT1 CYREG_USB_SIE_EP3_CNT1
#define USBUART_USB__SIE_EP3_CR0 CYREG_USB_SIE_EP3_CR0
#define USBUART_USB__SIE_EP4_CNT0 CYREG_USB_SIE_EP4_CNT0
#define USBUART_USB__SIE_EP4_CNT1 CYREG_USB_SIE_EP4_CNT1
#define USBUART_USB__SIE_EP4_CR0 CYREG_USB_SIE_EP4_CR0
#define USBUART_USB__SIE_EP5_CNT0 CYREG_USB_SIE_EP5_CNT0
#define USBUART_USB__SIE_EP5_CNT1 CYREG_USB_SIE_EP5_CNT1
#define USBUART_USB__SIE_EP5_CR0 CYREG_USB_SIE_EP5_CR0
#define USBUART_USB__SIE_EP6_CNT0 CYREG_USB_SIE_EP6_CNT0
#define USBUART_USB__SIE_EP6_CNT1 CYREG_USB_SIE_EP6_CNT1
#define USBUART_USB__SIE_EP6_CR0 CYREG_USB_SIE_EP6_CR0
#define USBUART_USB__SIE_EP7_CNT0 CYREG_USB_SIE_EP7_CNT0
#define USBUART_USB__SIE_EP7_CNT1 CYREG_USB_SIE_EP7_CNT1
#define USBUART_USB__SIE_EP7_CR0 CYREG_USB_SIE_EP7_CR0
#define USBUART_USB__SIE_EP8_CNT0 CYREG_USB_SIE_EP8_CNT0
#define USBUART_USB__SIE_EP8_CNT1 CYREG_USB_SIE_EP8_CNT1
#define USBUART_USB__SIE_EP8_CR0 CYREG_USB_SIE_EP8_CR0
#define USBUART_USB__SOF0 CYREG_USB_SOF0
#define USBUART_USB__SOF1 CYREG_USB_SOF1
#define USBUART_USB__USB_CLK_EN CYREG_USB_USB_CLK_EN
#define USBUART_USB__USBIO_CR0 CYREG_USB_USBIO_CR0
#define USBUART_USB__USBIO_CR1 CYREG_USB_USBIO_CR1
#define USBUART_USB__USBIO_CR2 CYREG_USB_USBIO_CR2

/* Filter_DFB */
#define Filter_DFB__ACU_SRAM_DATA CYREG_DFB0_ACU_SRAM_DATA_MBASE
#define Filter_DFB__COHER CYREG_DFB0_COHER
#define Filter_DFB__CR CYREG_DFB0_CR
#define Filter_DFB__CSA_SRAM_DATA CYREG_DFB0_CSA_SRAM_DATA_MBASE
#define Filter_DFB__CSB_SRAM_DATA CYREG_DFB0_CSB_SRAM_DATA_MBASE
#define Filter_DFB__DALIGN CYREG_DFB0_DALIGN
#define Filter_DFB__DMA_CTRL CYREG_DFB0_DMA_CTRL
#define Filter_DFB__DPA_SRAM_DATA CYREG_DFB0_DPA_SRAM_DATA_MBASE
#define Filter_DFB__DPB_SRAM_DATA CYREG_DFB0_DPB_SRAM_DATA_MBASE
#define Filter_DFB__DSI_CTRL CYREG_DFB0_DSI_CTRL
#define Filter_DFB__FSM_SRAM_DATA CYREG_DFB0_FSM_SRAM_DATA_MBASE
#define Filter_DFB__HOLDA CYREG_DFB0_HOLDA
#define Filter_DFB__HOLDAH CYREG_DFB0_HOLDAH
#define Filter_DFB__HOLDAM CYREG_DFB0_HOLDAM
#define Filter_DFB__HOLDAS CYREG_DFB0_HOLDAS
#define Filter_DFB__HOLDB CYREG_DFB0_HOLDB
#define Filter_DFB__HOLDBH CYREG_DFB0_HOLDBH
#define Filter_DFB__HOLDBM CYREG_DFB0_HOLDBM
#define Filter_DFB__HOLDBS CYREG_DFB0_HOLDBS
#define Filter_DFB__INT_CTRL CYREG_DFB0_INT_CTRL
#define Filter_DFB__PM_ACT_CFG CYREG_PM_ACT_CFG6
#define Filter_DFB__PM_ACT_MSK 0x10u
#define Filter_DFB__PM_STBY_CFG CYREG_PM_STBY_CFG6
#define Filter_DFB__PM_STBY_MSK 0x10u
#define Filter_DFB__RAM_DIR CYREG_DFB0_RAM_DIR
#define Filter_DFB__RAM_EN CYREG_DFB0_RAM_EN
#define Filter_DFB__SEMA CYREG_DFB0_SEMA
#define Filter_DFB__SR CYREG_DFB0_SR
#define Filter_DFB__STAGEA CYREG_DFB0_STAGEA
#define Filter_DFB__STAGEAH CYREG_DFB0_STAGEAH
#define Filter_DFB__STAGEAM CYREG_DFB0_STAGEAM
#define Filter_DFB__STAGEB CYREG_DFB0_STAGEB
#define Filter_DFB__STAGEBH CYREG_DFB0_STAGEBH
#define Filter_DFB__STAGEBM CYREG_DFB0_STAGEBM

/* ISR_Matrix */
#define ISR_Matrix__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ISR_Matrix__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ISR_Matrix__INTC_MASK 0x02u
#define ISR_Matrix__INTC_NUMBER 1
#define ISR_Matrix__INTC_PRIOR_NUM 7
#define ISR_Matrix__INTC_PRIOR_REG CYREG_NVIC_PRI_1
#define ISR_Matrix__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ISR_Matrix__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* USBUART_dm */
#define USBUART_dm__0__MASK 0x80u
#define USBUART_dm__0__PC CYREG_PRT15_PC7
#define USBUART_dm__0__PORT 15
#define USBUART_dm__0__SHIFT 7
#define USBUART_dm__AG CYREG_PRT15_AG
#define USBUART_dm__AMUX CYREG_PRT15_AMUX
#define USBUART_dm__BIE CYREG_PRT15_BIE
#define USBUART_dm__BIT_MASK CYREG_PRT15_BIT_MASK
#define USBUART_dm__BYP CYREG_PRT15_BYP
#define USBUART_dm__CTL CYREG_PRT15_CTL
#define USBUART_dm__dm__MASK 0x80u
#define USBUART_dm__dm__PC CYREG_PRT15_PC7
#define USBUART_dm__dm__PORT 15
#define USBUART_dm__dm__SHIFT 7
#define USBUART_dm__DM0 CYREG_PRT15_DM0
#define USBUART_dm__DM1 CYREG_PRT15_DM1
#define USBUART_dm__DM2 CYREG_PRT15_DM2
#define USBUART_dm__DR CYREG_PRT15_DR
#define USBUART_dm__INP_DIS CYREG_PRT15_INP_DIS
#define USBUART_dm__LCD_COM_SEG CYREG_PRT15_LCD_COM_SEG
#define USBUART_dm__LCD_EN CYREG_PRT15_LCD_EN
#define USBUART_dm__PORT 15
#define USBUART_dm__PRT CYREG_PRT15_PRT
#define USBUART_dm__PRTDSI__CAPS_SEL CYREG_PRT15_CAPS_SEL
#define USBUART_dm__PRTDSI__DBL_SYNC_IN CYREG_PRT15_DBL_SYNC_IN
#define USBUART_dm__PRTDSI__OE_SEL0 CYREG_PRT15_OE_SEL0
#define USBUART_dm__PRTDSI__OE_SEL1 CYREG_PRT15_OE_SEL1
#define USBUART_dm__PRTDSI__OUT_SEL0 CYREG_PRT15_OUT_SEL0
#define USBUART_dm__PRTDSI__OUT_SEL1 CYREG_PRT15_OUT_SEL1
#define USBUART_dm__PRTDSI__SYNC_OUT CYREG_PRT15_SYNC_OUT
#define USBUART_dm__PS CYREG_PRT15_PS
#define USBUART_dm__SLW CYREG_PRT15_SLW

/* USBUART_dp */
#define USBUART_dp__0__MASK 0x40u
#define USBUART_dp__0__PC CYREG_PRT15_PC6
#define USBUART_dp__0__PORT 15
#define USBUART_dp__0__SHIFT 6
#define USBUART_dp__AG CYREG_PRT15_AG
#define USBUART_dp__AMUX CYREG_PRT15_AMUX
#define USBUART_dp__BIE CYREG_PRT15_BIE
#define USBUART_dp__BIT_MASK CYREG_PRT15_BIT_MASK
#define USBUART_dp__BYP CYREG_PRT15_BYP
#define USBUART_dp__CTL CYREG_PRT15_CTL
#define USBUART_dp__DM0 CYREG_PRT15_DM0
#define USBUART_dp__DM1 CYREG_PRT15_DM1
#define USBUART_dp__DM2 CYREG_PRT15_DM2
#define USBUART_dp__dp__MASK 0x40u
#define USBUART_dp__dp__PC CYREG_PRT15_PC6
#define USBUART_dp__dp__PORT 15
#define USBUART_dp__dp__SHIFT 6
#define USBUART_dp__DR CYREG_PRT15_DR
#define USBUART_dp__INP_DIS CYREG_PRT15_INP_DIS
#define USBUART_dp__LCD_COM_SEG CYREG_PRT15_LCD_COM_SEG
#define USBUART_dp__LCD_EN CYREG_PRT15_LCD_EN
#define USBUART_dp__PORT 15
#define USBUART_dp__PRT CYREG_PRT15_PRT
#define USBUART_dp__PRTDSI__CAPS_SEL CYREG_PRT15_CAPS_SEL
#define USBUART_dp__PRTDSI__DBL_SYNC_IN CYREG_PRT15_DBL_SYNC_IN
#define USBUART_dp__PRTDSI__OE_SEL0 CYREG_PRT15_OE_SEL0
#define USBUART_dp__PRTDSI__OE_SEL1 CYREG_PRT15_OE_SEL1
#define USBUART_dp__PRTDSI__OUT_SEL0 CYREG_PRT15_OUT_SEL0
#define USBUART_dp__PRTDSI__OUT_SEL1 CYREG_PRT15_OUT_SEL1
#define USBUART_dp__PRTDSI__SYNC_OUT CYREG_PRT15_SYNC_OUT
#define USBUART_dp__PS CYREG_PRT15_PS
#define USBUART_dp__SLW CYREG_PRT15_SLW

/* DMA_ADC_A */
#define DMA_ADC_A__DRQ_CTL CYREG_IDMUX_DRQ_CTL3
#define DMA_ADC_A__DRQ_NUMBER 12
#define DMA_ADC_A__NUMBEROF_TDS 0
#define DMA_ADC_A__PRIORITY 2
#define DMA_ADC_A__TERMIN_EN 0
#define DMA_ADC_A__TERMIN_SEL 0
#define DMA_ADC_A__TERMOUT0_EN 1
#define DMA_ADC_A__TERMOUT0_SEL 12
#define DMA_ADC_A__TERMOUT1_EN 1
#define DMA_ADC_A__TERMOUT1_SEL 6

/* DMA_ADC_B */
#define DMA_ADC_B__DRQ_CTL CYREG_IDMUX_DRQ_CTL3
#define DMA_ADC_B__DRQ_NUMBER 13
#define DMA_ADC_B__NUMBEROF_TDS 0
#define DMA_ADC_B__PRIORITY 2
#define DMA_ADC_B__TERMIN_EN 0
#define DMA_ADC_B__TERMIN_SEL 0
#define DMA_ADC_B__TERMOUT0_EN 0
#define DMA_ADC_B__TERMOUT0_SEL 0
#define DMA_ADC_B__TERMOUT1_EN 0
#define DMA_ADC_B__TERMOUT1_SEL 0

/* DMA_Debug */
#define DMA_Debug__DRQ_CTL CYREG_IDMUX_DRQ_CTL0
#define DMA_Debug__DRQ_NUMBER 2
#define DMA_Debug__NUMBEROF_TDS 0
#define DMA_Debug__PRIORITY 2
#define DMA_Debug__TERMIN_EN 0
#define DMA_Debug__TERMIN_SEL 0
#define DMA_Debug__TERMOUT0_EN 0
#define DMA_Debug__TERMOUT0_SEL 0
#define DMA_Debug__TERMOUT1_EN 0
#define DMA_Debug__TERMOUT1_SEL 0

/* Matrix_CR */
#define Matrix_CR_ctrl_reg__0__MASK 0x01u
#define Matrix_CR_ctrl_reg__0__POS 0
#define Matrix_CR_ctrl_reg__1__MASK 0x02u
#define Matrix_CR_ctrl_reg__1__POS 1
#define Matrix_CR_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB06_07_ACTL
#define Matrix_CR_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB06_07_CTL
#define Matrix_CR_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB06_07_CTL
#define Matrix_CR_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB06_07_CTL
#define Matrix_CR_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB06_07_CTL
#define Matrix_CR_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB06_07_MSK
#define Matrix_CR_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB06_07_MSK
#define Matrix_CR_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB06_07_MSK
#define Matrix_CR_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB06_07_MSK
#define Matrix_CR_ctrl_reg__2__MASK 0x04u
#define Matrix_CR_ctrl_reg__2__POS 2
#define Matrix_CR_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB06_ACTL
#define Matrix_CR_ctrl_reg__CONTROL_REG CYREG_B0_UDB06_CTL
#define Matrix_CR_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB06_ST_CTL
#define Matrix_CR_ctrl_reg__COUNT_REG CYREG_B0_UDB06_CTL
#define Matrix_CR_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB06_ST_CTL
#define Matrix_CR_ctrl_reg__MASK 0x07u
#define Matrix_CR_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB06_MSK_ACTL
#define Matrix_CR_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB06_MSK_ACTL
#define Matrix_CR_ctrl_reg__PERIOD_REG CYREG_B0_UDB06_MSK

/* Matrix_SR */
#define Matrix_SR_sts_reg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB14_15_ACTL
#define Matrix_SR_sts_reg__16BIT_STATUS_REG CYREG_B0_UDB14_15_ST
#define Matrix_SR_sts_reg__MASK 0x00u
#define Matrix_SR_sts_reg__MASK_REG CYREG_B0_UDB14_MSK
#define Matrix_SR_sts_reg__STATUS_AUX_CTL_REG CYREG_B0_UDB14_ACTL
#define Matrix_SR_sts_reg__STATUS_REG CYREG_B0_UDB14_ST

/* Pin_Debug */
#define Pin_Debug__0__MASK 0x80u
#define Pin_Debug__0__PC CYREG_PRT3_PC7
#define Pin_Debug__0__PORT 3
#define Pin_Debug__0__SHIFT 7
#define Pin_Debug__AG CYREG_PRT3_AG
#define Pin_Debug__AMUX CYREG_PRT3_AMUX
#define Pin_Debug__BIE CYREG_PRT3_BIE
#define Pin_Debug__BIT_MASK CYREG_PRT3_BIT_MASK
#define Pin_Debug__BYP CYREG_PRT3_BYP
#define Pin_Debug__CTL CYREG_PRT3_CTL
#define Pin_Debug__DM0 CYREG_PRT3_DM0
#define Pin_Debug__DM1 CYREG_PRT3_DM1
#define Pin_Debug__DM2 CYREG_PRT3_DM2
#define Pin_Debug__DR CYREG_PRT3_DR
#define Pin_Debug__INP_DIS CYREG_PRT3_INP_DIS
#define Pin_Debug__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Pin_Debug__LCD_EN CYREG_PRT3_LCD_EN
#define Pin_Debug__PORT 3
#define Pin_Debug__PRT CYREG_PRT3_PRT
#define Pin_Debug__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Pin_Debug__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Pin_Debug__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Pin_Debug__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Pin_Debug__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Pin_Debug__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Pin_Debug__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Pin_Debug__PS CYREG_PRT3_PS
#define Pin_Debug__SLW CYREG_PRT3_SLW

/* Pin_Row_A */
#define Pin_Row_A__0__MASK 0x01u
#define Pin_Row_A__0__PC CYREG_PRT4_PC0
#define Pin_Row_A__0__PORT 4
#define Pin_Row_A__0__SHIFT 0
#define Pin_Row_A__1__MASK 0x04u
#define Pin_Row_A__1__PC CYREG_PRT4_PC2
#define Pin_Row_A__1__PORT 4
#define Pin_Row_A__1__SHIFT 2
#define Pin_Row_A__2__MASK 0x10u
#define Pin_Row_A__2__PC CYREG_PRT4_PC4
#define Pin_Row_A__2__PORT 4
#define Pin_Row_A__2__SHIFT 4
#define Pin_Row_A__3__MASK 0x40u
#define Pin_Row_A__3__PC CYREG_PRT4_PC6
#define Pin_Row_A__3__PORT 4
#define Pin_Row_A__3__SHIFT 6
#define Pin_Row_A__4__MASK 0x02u
#define Pin_Row_A__4__PC CYREG_PRT4_PC1
#define Pin_Row_A__4__PORT 4
#define Pin_Row_A__4__SHIFT 1
#define Pin_Row_A__5__MASK 0x08u
#define Pin_Row_A__5__PC CYREG_PRT4_PC3
#define Pin_Row_A__5__PORT 4
#define Pin_Row_A__5__SHIFT 3
#define Pin_Row_A__6__MASK 0x20u
#define Pin_Row_A__6__PC CYREG_PRT4_PC5
#define Pin_Row_A__6__PORT 4
#define Pin_Row_A__6__SHIFT 5
#define Pin_Row_A__7__MASK 0x80u
#define Pin_Row_A__7__PC CYREG_PRT4_PC7
#define Pin_Row_A__7__PORT 4
#define Pin_Row_A__7__SHIFT 7
#define Pin_Row_A__AG CYREG_PRT4_AG
#define Pin_Row_A__AMUX CYREG_PRT4_AMUX
#define Pin_Row_A__BIE CYREG_PRT4_BIE
#define Pin_Row_A__BIT_MASK CYREG_PRT4_BIT_MASK
#define Pin_Row_A__BYP CYREG_PRT4_BYP
#define Pin_Row_A__CTL CYREG_PRT4_CTL
#define Pin_Row_A__DM0 CYREG_PRT4_DM0
#define Pin_Row_A__DM1 CYREG_PRT4_DM1
#define Pin_Row_A__DM2 CYREG_PRT4_DM2
#define Pin_Row_A__DR CYREG_PRT4_DR
#define Pin_Row_A__INP_DIS CYREG_PRT4_INP_DIS
#define Pin_Row_A__LCD_COM_SEG CYREG_PRT4_LCD_COM_SEG
#define Pin_Row_A__LCD_EN CYREG_PRT4_LCD_EN
#define Pin_Row_A__PORT 4
#define Pin_Row_A__PRT CYREG_PRT4_PRT
#define Pin_Row_A__PRTDSI__CAPS_SEL CYREG_PRT4_CAPS_SEL
#define Pin_Row_A__PRTDSI__DBL_SYNC_IN CYREG_PRT4_DBL_SYNC_IN
#define Pin_Row_A__PRTDSI__OE_SEL0 CYREG_PRT4_OE_SEL0
#define Pin_Row_A__PRTDSI__OE_SEL1 CYREG_PRT4_OE_SEL1
#define Pin_Row_A__PRTDSI__OUT_SEL0 CYREG_PRT4_OUT_SEL0
#define Pin_Row_A__PRTDSI__OUT_SEL1 CYREG_PRT4_OUT_SEL1
#define Pin_Row_A__PRTDSI__SYNC_OUT CYREG_PRT4_SYNC_OUT
#define Pin_Row_A__PS CYREG_PRT4_PS
#define Pin_Row_A__SLW CYREG_PRT4_SLW

/* Pin_Row_B */
#define Pin_Row_B__0__MASK 0x01u
#define Pin_Row_B__0__PC CYREG_PRT5_PC0
#define Pin_Row_B__0__PORT 5
#define Pin_Row_B__0__SHIFT 0
#define Pin_Row_B__1__MASK 0x04u
#define Pin_Row_B__1__PC CYREG_PRT5_PC2
#define Pin_Row_B__1__PORT 5
#define Pin_Row_B__1__SHIFT 2
#define Pin_Row_B__2__MASK 0x10u
#define Pin_Row_B__2__PC CYREG_PRT5_PC4
#define Pin_Row_B__2__PORT 5
#define Pin_Row_B__2__SHIFT 4
#define Pin_Row_B__3__MASK 0x40u
#define Pin_Row_B__3__PC CYREG_PRT5_PC6
#define Pin_Row_B__3__PORT 5
#define Pin_Row_B__3__SHIFT 6
#define Pin_Row_B__4__MASK 0x02u
#define Pin_Row_B__4__PC CYREG_PRT5_PC1
#define Pin_Row_B__4__PORT 5
#define Pin_Row_B__4__SHIFT 1
#define Pin_Row_B__5__MASK 0x08u
#define Pin_Row_B__5__PC CYREG_PRT5_PC3
#define Pin_Row_B__5__PORT 5
#define Pin_Row_B__5__SHIFT 3
#define Pin_Row_B__6__MASK 0x20u
#define Pin_Row_B__6__PC CYREG_PRT5_PC5
#define Pin_Row_B__6__PORT 5
#define Pin_Row_B__6__SHIFT 5
#define Pin_Row_B__7__MASK 0x80u
#define Pin_Row_B__7__PC CYREG_PRT5_PC7
#define Pin_Row_B__7__PORT 5
#define Pin_Row_B__7__SHIFT 7
#define Pin_Row_B__AG CYREG_PRT5_AG
#define Pin_Row_B__AMUX CYREG_PRT5_AMUX
#define Pin_Row_B__BIE CYREG_PRT5_BIE
#define Pin_Row_B__BIT_MASK CYREG_PRT5_BIT_MASK
#define Pin_Row_B__BYP CYREG_PRT5_BYP
#define Pin_Row_B__CTL CYREG_PRT5_CTL
#define Pin_Row_B__DM0 CYREG_PRT5_DM0
#define Pin_Row_B__DM1 CYREG_PRT5_DM1
#define Pin_Row_B__DM2 CYREG_PRT5_DM2
#define Pin_Row_B__DR CYREG_PRT5_DR
#define Pin_Row_B__INP_DIS CYREG_PRT5_INP_DIS
#define Pin_Row_B__LCD_COM_SEG CYREG_PRT5_LCD_COM_SEG
#define Pin_Row_B__LCD_EN CYREG_PRT5_LCD_EN
#define Pin_Row_B__PORT 5
#define Pin_Row_B__PRT CYREG_PRT5_PRT
#define Pin_Row_B__PRTDSI__CAPS_SEL CYREG_PRT5_CAPS_SEL
#define Pin_Row_B__PRTDSI__DBL_SYNC_IN CYREG_PRT5_DBL_SYNC_IN
#define Pin_Row_B__PRTDSI__OE_SEL0 CYREG_PRT5_OE_SEL0
#define Pin_Row_B__PRTDSI__OE_SEL1 CYREG_PRT5_OE_SEL1
#define Pin_Row_B__PRTDSI__OUT_SEL0 CYREG_PRT5_OUT_SEL0
#define Pin_Row_B__PRTDSI__OUT_SEL1 CYREG_PRT5_OUT_SEL1
#define Pin_Row_B__PRTDSI__SYNC_OUT CYREG_PRT5_SYNC_OUT
#define Pin_Row_B__PS CYREG_PRT5_PS
#define Pin_Row_B__SLW CYREG_PRT5_SLW

/* Pin_Vref */
#define Pin_Vref__0__MASK 0x40u
#define Pin_Vref__0__PC CYREG_PRT3_PC6
#define Pin_Vref__0__PORT 3
#define Pin_Vref__0__SHIFT 6
#define Pin_Vref__AG CYREG_PRT3_AG
#define Pin_Vref__AMUX CYREG_PRT3_AMUX
#define Pin_Vref__BIE CYREG_PRT3_BIE
#define Pin_Vref__BIT_MASK CYREG_PRT3_BIT_MASK
#define Pin_Vref__BYP CYREG_PRT3_BYP
#define Pin_Vref__CTL CYREG_PRT3_CTL
#define Pin_Vref__DM0 CYREG_PRT3_DM0
#define Pin_Vref__DM1 CYREG_PRT3_DM1
#define Pin_Vref__DM2 CYREG_PRT3_DM2
#define Pin_Vref__DR CYREG_PRT3_DR
#define Pin_Vref__INP_DIS CYREG_PRT3_INP_DIS
#define Pin_Vref__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Pin_Vref__LCD_EN CYREG_PRT3_LCD_EN
#define Pin_Vref__PORT 3
#define Pin_Vref__PRT CYREG_PRT3_PRT
#define Pin_Vref__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Pin_Vref__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Pin_Vref__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Pin_Vref__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Pin_Vref__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Pin_Vref__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Pin_Vref__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Pin_Vref__PS CYREG_PRT3_PS
#define Pin_Vref__SLW CYREG_PRT3_SLW

/* Pin_Col */
#define Pin_Col__0__AG CYREG_PRT6_AG
#define Pin_Col__0__AMUX CYREG_PRT6_AMUX
#define Pin_Col__0__BIE CYREG_PRT6_BIE
#define Pin_Col__0__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__0__BYP CYREG_PRT6_BYP
#define Pin_Col__0__CTL CYREG_PRT6_CTL
#define Pin_Col__0__DM0 CYREG_PRT6_DM0
#define Pin_Col__0__DM1 CYREG_PRT6_DM1
#define Pin_Col__0__DM2 CYREG_PRT6_DM2
#define Pin_Col__0__DR CYREG_PRT6_DR
#define Pin_Col__0__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__0__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__0__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__0__MASK 0x01u
#define Pin_Col__0__PC CYREG_PRT6_PC0
#define Pin_Col__0__PORT 6
#define Pin_Col__0__PRT CYREG_PRT6_PRT
#define Pin_Col__0__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__0__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__0__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__0__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__0__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__0__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__0__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__0__PS CYREG_PRT6_PS
#define Pin_Col__0__SHIFT 0
#define Pin_Col__0__SLW CYREG_PRT6_SLW
#define Pin_Col__1__AG CYREG_PRT6_AG
#define Pin_Col__1__AMUX CYREG_PRT6_AMUX
#define Pin_Col__1__BIE CYREG_PRT6_BIE
#define Pin_Col__1__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__1__BYP CYREG_PRT6_BYP
#define Pin_Col__1__CTL CYREG_PRT6_CTL
#define Pin_Col__1__DM0 CYREG_PRT6_DM0
#define Pin_Col__1__DM1 CYREG_PRT6_DM1
#define Pin_Col__1__DM2 CYREG_PRT6_DM2
#define Pin_Col__1__DR CYREG_PRT6_DR
#define Pin_Col__1__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__1__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__1__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__1__MASK 0x04u
#define Pin_Col__1__PC CYREG_PRT6_PC2
#define Pin_Col__1__PORT 6
#define Pin_Col__1__PRT CYREG_PRT6_PRT
#define Pin_Col__1__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__1__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__1__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__1__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__1__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__1__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__1__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__1__PS CYREG_PRT6_PS
#define Pin_Col__1__SHIFT 2
#define Pin_Col__1__SLW CYREG_PRT6_SLW
#define Pin_Col__10__AG CYREG_PRT12_AG
#define Pin_Col__10__BIE CYREG_PRT12_BIE
#define Pin_Col__10__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__10__BYP CYREG_PRT12_BYP
#define Pin_Col__10__DM0 CYREG_PRT12_DM0
#define Pin_Col__10__DM1 CYREG_PRT12_DM1
#define Pin_Col__10__DM2 CYREG_PRT12_DM2
#define Pin_Col__10__DR CYREG_PRT12_DR
#define Pin_Col__10__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__10__MASK 0x04u
#define Pin_Col__10__PC CYREG_PRT12_PC2
#define Pin_Col__10__PORT 12
#define Pin_Col__10__PRT CYREG_PRT12_PRT
#define Pin_Col__10__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__10__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__10__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__10__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__10__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__10__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__10__PS CYREG_PRT12_PS
#define Pin_Col__10__SHIFT 2
#define Pin_Col__10__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__10__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__10__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__10__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__10__SLW CYREG_PRT12_SLW
#define Pin_Col__11__AG CYREG_PRT12_AG
#define Pin_Col__11__BIE CYREG_PRT12_BIE
#define Pin_Col__11__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__11__BYP CYREG_PRT12_BYP
#define Pin_Col__11__DM0 CYREG_PRT12_DM0
#define Pin_Col__11__DM1 CYREG_PRT12_DM1
#define Pin_Col__11__DM2 CYREG_PRT12_DM2
#define Pin_Col__11__DR CYREG_PRT12_DR
#define Pin_Col__11__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__11__MASK 0x08u
#define Pin_Col__11__PC CYREG_PRT12_PC3
#define Pin_Col__11__PORT 12
#define Pin_Col__11__PRT CYREG_PRT12_PRT
#define Pin_Col__11__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__11__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__11__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__11__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__11__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__11__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__11__PS CYREG_PRT12_PS
#define Pin_Col__11__SHIFT 3
#define Pin_Col__11__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__11__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__11__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__11__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__11__SLW CYREG_PRT12_SLW
#define Pin_Col__12__AG CYREG_PRT12_AG
#define Pin_Col__12__BIE CYREG_PRT12_BIE
#define Pin_Col__12__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__12__BYP CYREG_PRT12_BYP
#define Pin_Col__12__DM0 CYREG_PRT12_DM0
#define Pin_Col__12__DM1 CYREG_PRT12_DM1
#define Pin_Col__12__DM2 CYREG_PRT12_DM2
#define Pin_Col__12__DR CYREG_PRT12_DR
#define Pin_Col__12__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__12__MASK 0x10u
#define Pin_Col__12__PC CYREG_PRT12_PC4
#define Pin_Col__12__PORT 12
#define Pin_Col__12__PRT CYREG_PRT12_PRT
#define Pin_Col__12__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__12__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__12__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__12__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__12__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__12__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__12__PS CYREG_PRT12_PS
#define Pin_Col__12__SHIFT 4
#define Pin_Col__12__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__12__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__12__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__12__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__12__SLW CYREG_PRT12_SLW
#define Pin_Col__13__AG CYREG_PRT12_AG
#define Pin_Col__13__BIE CYREG_PRT12_BIE
#define Pin_Col__13__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__13__BYP CYREG_PRT12_BYP
#define Pin_Col__13__DM0 CYREG_PRT12_DM0
#define Pin_Col__13__DM1 CYREG_PRT12_DM1
#define Pin_Col__13__DM2 CYREG_PRT12_DM2
#define Pin_Col__13__DR CYREG_PRT12_DR
#define Pin_Col__13__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__13__MASK 0x20u
#define Pin_Col__13__PC CYREG_PRT12_PC5
#define Pin_Col__13__PORT 12
#define Pin_Col__13__PRT CYREG_PRT12_PRT
#define Pin_Col__13__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__13__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__13__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__13__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__13__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__13__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__13__PS CYREG_PRT12_PS
#define Pin_Col__13__SHIFT 5
#define Pin_Col__13__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__13__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__13__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__13__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__13__SLW CYREG_PRT12_SLW
#define Pin_Col__14__AG CYREG_PRT12_AG
#define Pin_Col__14__BIE CYREG_PRT12_BIE
#define Pin_Col__14__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__14__BYP CYREG_PRT12_BYP
#define Pin_Col__14__DM0 CYREG_PRT12_DM0
#define Pin_Col__14__DM1 CYREG_PRT12_DM1
#define Pin_Col__14__DM2 CYREG_PRT12_DM2
#define Pin_Col__14__DR CYREG_PRT12_DR
#define Pin_Col__14__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__14__MASK 0x40u
#define Pin_Col__14__PC CYREG_PRT12_PC6
#define Pin_Col__14__PORT 12
#define Pin_Col__14__PRT CYREG_PRT12_PRT
#define Pin_Col__14__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__14__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__14__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__14__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__14__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__14__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__14__PS CYREG_PRT12_PS
#define Pin_Col__14__SHIFT 6
#define Pin_Col__14__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__14__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__14__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__14__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__14__SLW CYREG_PRT12_SLW
#define Pin_Col__15__AG CYREG_PRT12_AG
#define Pin_Col__15__BIE CYREG_PRT12_BIE
#define Pin_Col__15__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__15__BYP CYREG_PRT12_BYP
#define Pin_Col__15__DM0 CYREG_PRT12_DM0
#define Pin_Col__15__DM1 CYREG_PRT12_DM1
#define Pin_Col__15__DM2 CYREG_PRT12_DM2
#define Pin_Col__15__DR CYREG_PRT12_DR
#define Pin_Col__15__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__15__MASK 0x80u
#define Pin_Col__15__PC CYREG_PRT12_PC7
#define Pin_Col__15__PORT 12
#define Pin_Col__15__PRT CYREG_PRT12_PRT
#define Pin_Col__15__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__15__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__15__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__15__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__15__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__15__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__15__PS CYREG_PRT12_PS
#define Pin_Col__15__SHIFT 7
#define Pin_Col__15__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__15__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__15__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__15__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__15__SLW CYREG_PRT12_SLW
#define Pin_Col__2__AG CYREG_PRT6_AG
#define Pin_Col__2__AMUX CYREG_PRT6_AMUX
#define Pin_Col__2__BIE CYREG_PRT6_BIE
#define Pin_Col__2__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__2__BYP CYREG_PRT6_BYP
#define Pin_Col__2__CTL CYREG_PRT6_CTL
#define Pin_Col__2__DM0 CYREG_PRT6_DM0
#define Pin_Col__2__DM1 CYREG_PRT6_DM1
#define Pin_Col__2__DM2 CYREG_PRT6_DM2
#define Pin_Col__2__DR CYREG_PRT6_DR
#define Pin_Col__2__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__2__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__2__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__2__MASK 0x10u
#define Pin_Col__2__PC CYREG_PRT6_PC4
#define Pin_Col__2__PORT 6
#define Pin_Col__2__PRT CYREG_PRT6_PRT
#define Pin_Col__2__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__2__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__2__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__2__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__2__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__2__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__2__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__2__PS CYREG_PRT6_PS
#define Pin_Col__2__SHIFT 4
#define Pin_Col__2__SLW CYREG_PRT6_SLW
#define Pin_Col__3__AG CYREG_PRT6_AG
#define Pin_Col__3__AMUX CYREG_PRT6_AMUX
#define Pin_Col__3__BIE CYREG_PRT6_BIE
#define Pin_Col__3__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__3__BYP CYREG_PRT6_BYP
#define Pin_Col__3__CTL CYREG_PRT6_CTL
#define Pin_Col__3__DM0 CYREG_PRT6_DM0
#define Pin_Col__3__DM1 CYREG_PRT6_DM1
#define Pin_Col__3__DM2 CYREG_PRT6_DM2
#define Pin_Col__3__DR CYREG_PRT6_DR
#define Pin_Col__3__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__3__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__3__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__3__MASK 0x40u
#define Pin_Col__3__PC CYREG_PRT6_PC6
#define Pin_Col__3__PORT 6
#define Pin_Col__3__PRT CYREG_PRT6_PRT
#define Pin_Col__3__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__3__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__3__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__3__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__3__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__3__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__3__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__3__PS CYREG_PRT6_PS
#define Pin_Col__3__SHIFT 6
#define Pin_Col__3__SLW CYREG_PRT6_SLW
#define Pin_Col__4__AG CYREG_PRT6_AG
#define Pin_Col__4__AMUX CYREG_PRT6_AMUX
#define Pin_Col__4__BIE CYREG_PRT6_BIE
#define Pin_Col__4__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__4__BYP CYREG_PRT6_BYP
#define Pin_Col__4__CTL CYREG_PRT6_CTL
#define Pin_Col__4__DM0 CYREG_PRT6_DM0
#define Pin_Col__4__DM1 CYREG_PRT6_DM1
#define Pin_Col__4__DM2 CYREG_PRT6_DM2
#define Pin_Col__4__DR CYREG_PRT6_DR
#define Pin_Col__4__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__4__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__4__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__4__MASK 0x02u
#define Pin_Col__4__PC CYREG_PRT6_PC1
#define Pin_Col__4__PORT 6
#define Pin_Col__4__PRT CYREG_PRT6_PRT
#define Pin_Col__4__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__4__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__4__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__4__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__4__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__4__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__4__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__4__PS CYREG_PRT6_PS
#define Pin_Col__4__SHIFT 1
#define Pin_Col__4__SLW CYREG_PRT6_SLW
#define Pin_Col__5__AG CYREG_PRT6_AG
#define Pin_Col__5__AMUX CYREG_PRT6_AMUX
#define Pin_Col__5__BIE CYREG_PRT6_BIE
#define Pin_Col__5__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__5__BYP CYREG_PRT6_BYP
#define Pin_Col__5__CTL CYREG_PRT6_CTL
#define Pin_Col__5__DM0 CYREG_PRT6_DM0
#define Pin_Col__5__DM1 CYREG_PRT6_DM1
#define Pin_Col__5__DM2 CYREG_PRT6_DM2
#define Pin_Col__5__DR CYREG_PRT6_DR
#define Pin_Col__5__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__5__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__5__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__5__MASK 0x08u
#define Pin_Col__5__PC CYREG_PRT6_PC3
#define Pin_Col__5__PORT 6
#define Pin_Col__5__PRT CYREG_PRT6_PRT
#define Pin_Col__5__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__5__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__5__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__5__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__5__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__5__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__5__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__5__PS CYREG_PRT6_PS
#define Pin_Col__5__SHIFT 3
#define Pin_Col__5__SLW CYREG_PRT6_SLW
#define Pin_Col__6__AG CYREG_PRT6_AG
#define Pin_Col__6__AMUX CYREG_PRT6_AMUX
#define Pin_Col__6__BIE CYREG_PRT6_BIE
#define Pin_Col__6__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__6__BYP CYREG_PRT6_BYP
#define Pin_Col__6__CTL CYREG_PRT6_CTL
#define Pin_Col__6__DM0 CYREG_PRT6_DM0
#define Pin_Col__6__DM1 CYREG_PRT6_DM1
#define Pin_Col__6__DM2 CYREG_PRT6_DM2
#define Pin_Col__6__DR CYREG_PRT6_DR
#define Pin_Col__6__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__6__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__6__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__6__MASK 0x20u
#define Pin_Col__6__PC CYREG_PRT6_PC5
#define Pin_Col__6__PORT 6
#define Pin_Col__6__PRT CYREG_PRT6_PRT
#define Pin_Col__6__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__6__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__6__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__6__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__6__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__6__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__6__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__6__PS CYREG_PRT6_PS
#define Pin_Col__6__SHIFT 5
#define Pin_Col__6__SLW CYREG_PRT6_SLW
#define Pin_Col__7__AG CYREG_PRT6_AG
#define Pin_Col__7__AMUX CYREG_PRT6_AMUX
#define Pin_Col__7__BIE CYREG_PRT6_BIE
#define Pin_Col__7__BIT_MASK CYREG_PRT6_BIT_MASK
#define Pin_Col__7__BYP CYREG_PRT6_BYP
#define Pin_Col__7__CTL CYREG_PRT6_CTL
#define Pin_Col__7__DM0 CYREG_PRT6_DM0
#define Pin_Col__7__DM1 CYREG_PRT6_DM1
#define Pin_Col__7__DM2 CYREG_PRT6_DM2
#define Pin_Col__7__DR CYREG_PRT6_DR
#define Pin_Col__7__INP_DIS CYREG_PRT6_INP_DIS
#define Pin_Col__7__LCD_COM_SEG CYREG_PRT6_LCD_COM_SEG
#define Pin_Col__7__LCD_EN CYREG_PRT6_LCD_EN
#define Pin_Col__7__MASK 0x80u
#define Pin_Col__7__PC CYREG_PRT6_PC7
#define Pin_Col__7__PORT 6
#define Pin_Col__7__PRT CYREG_PRT6_PRT
#define Pin_Col__7__PRTDSI__CAPS_SEL CYREG_PRT6_CAPS_SEL
#define Pin_Col__7__PRTDSI__DBL_SYNC_IN CYREG_PRT6_DBL_SYNC_IN
#define Pin_Col__7__PRTDSI__OE_SEL0 CYREG_PRT6_OE_SEL0
#define Pin_Col__7__PRTDSI__OE_SEL1 CYREG_PRT6_OE_SEL1
#define Pin_Col__7__PRTDSI__OUT_SEL0 CYREG_PRT6_OUT_SEL0
#define Pin_Col__7__PRTDSI__OUT_SEL1 CYREG_PRT6_OUT_SEL1
#define Pin_Col__7__PRTDSI__SYNC_OUT CYREG_PRT6_SYNC_OUT
#define Pin_Col__7__PS CYREG_PRT6_PS
#define Pin_Col__7__SHIFT 7
#define Pin_Col__7__SLW CYREG_PRT6_SLW
#define Pin_Col__8__AG CYREG_PRT12_AG
#define Pin_Col__8__BIE CYREG_PRT12_BIE
#define Pin_Col__8__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__8__BYP CYREG_PRT12_BYP
#define Pin_Col__8__DM0 CYREG_PRT12_DM0
#define Pin_Col__8__DM1 CYREG_PRT12_DM1
#define Pin_Col__8__DM2 CYREG_PRT12_DM2
#define Pin_Col__8__DR CYREG_PRT12_DR
#define Pin_Col__8__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__8__MASK 0x01u
#define Pin_Col__8__PC CYREG_PRT12_PC0
#define Pin_Col__8__PORT 12
#define Pin_Col__8__PRT CYREG_PRT12_PRT
#define Pin_Col__8__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__8__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__8__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__8__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__8__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__8__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__8__PS CYREG_PRT12_PS
#define Pin_Col__8__SHIFT 0
#define Pin_Col__8__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__8__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__8__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__8__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__8__SLW CYREG_PRT12_SLW
#define Pin_Col__9__AG CYREG_PRT12_AG
#define Pin_Col__9__BIE CYREG_PRT12_BIE
#define Pin_Col__9__BIT_MASK CYREG_PRT12_BIT_MASK
#define Pin_Col__9__BYP CYREG_PRT12_BYP
#define Pin_Col__9__DM0 CYREG_PRT12_DM0
#define Pin_Col__9__DM1 CYREG_PRT12_DM1
#define Pin_Col__9__DM2 CYREG_PRT12_DM2
#define Pin_Col__9__DR CYREG_PRT12_DR
#define Pin_Col__9__INP_DIS CYREG_PRT12_INP_DIS
#define Pin_Col__9__MASK 0x02u
#define Pin_Col__9__PC CYREG_PRT12_PC1
#define Pin_Col__9__PORT 12
#define Pin_Col__9__PRT CYREG_PRT12_PRT
#define Pin_Col__9__PRTDSI__DBL_SYNC_IN CYREG_PRT12_DBL_SYNC_IN
#define Pin_Col__9__PRTDSI__OE_SEL0 CYREG_PRT12_OE_SEL0
#define Pin_Col__9__PRTDSI__OE_SEL1 CYREG_PRT12_OE_SEL1
#define Pin_Col__9__PRTDSI__OUT_SEL0 CYREG_PRT12_OUT_SEL0
#define Pin_Col__9__PRTDSI__OUT_SEL1 CYREG_PRT12_OUT_SEL1
#define Pin_Col__9__PRTDSI__SYNC_OUT CYREG_PRT12_SYNC_OUT
#define Pin_Col__9__PS CYREG_PRT12_PS
#define Pin_Col__9__SHIFT 1
#define Pin_Col__9__SIO_CFG CYREG_PRT12_SIO_CFG
#define Pin_Col__9__SIO_DIFF CYREG_PRT12_SIO_DIFF
#define Pin_Col__9__SIO_HYST_EN CYREG_PRT12_SIO_HYST_EN
#define Pin_Col__9__SIO_REG_HIFREQ CYREG_PRT12_SIO_REG_HIFREQ
#define Pin_Col__9__SLW CYREG_PRT12_SLW

/* Pin_1 */
#define Pin_1__0__MASK 0x01u
#define Pin_1__0__PC CYREG_PRT3_PC0
#define Pin_1__0__PORT 3
#define Pin_1__0__SHIFT 0
#define Pin_1__AG CYREG_PRT3_AG
#define Pin_1__AMUX CYREG_PRT3_AMUX
#define Pin_1__BIE CYREG_PRT3_BIE
#define Pin_1__BIT_MASK CYREG_PRT3_BIT_MASK
#define Pin_1__BYP CYREG_PRT3_BYP
#define Pin_1__CTL CYREG_PRT3_CTL
#define Pin_1__DM0 CYREG_PRT3_DM0
#define Pin_1__DM1 CYREG_PRT3_DM1
#define Pin_1__DM2 CYREG_PRT3_DM2
#define Pin_1__DR CYREG_PRT3_DR
#define Pin_1__INP_DIS CYREG_PRT3_INP_DIS
#define Pin_1__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Pin_1__LCD_EN CYREG_PRT3_LCD_EN
#define Pin_1__MASK 0x01u
#define Pin_1__PORT 3
#define Pin_1__PRT CYREG_PRT3_PRT
#define Pin_1__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Pin_1__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Pin_1__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Pin_1__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Pin_1__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Pin_1__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Pin_1__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Pin_1__PS CYREG_PRT3_PS
#define Pin_1__SHIFT 0
#define Pin_1__SLW CYREG_PRT3_SLW

/* Pin_2 */
#define Pin_2__0__MASK 0x02u
#define Pin_2__0__PC CYREG_PRT3_PC1
#define Pin_2__0__PORT 3
#define Pin_2__0__SHIFT 1
#define Pin_2__AG CYREG_PRT3_AG
#define Pin_2__AMUX CYREG_PRT3_AMUX
#define Pin_2__BIE CYREG_PRT3_BIE
#define Pin_2__BIT_MASK CYREG_PRT3_BIT_MASK
#define Pin_2__BYP CYREG_PRT3_BYP
#define Pin_2__CTL CYREG_PRT3_CTL
#define Pin_2__DM0 CYREG_PRT3_DM0
#define Pin_2__DM1 CYREG_PRT3_DM1
#define Pin_2__DM2 CYREG_PRT3_DM2
#define Pin_2__DR CYREG_PRT3_DR
#define Pin_2__INP_DIS CYREG_PRT3_INP_DIS
#define Pin_2__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Pin_2__LCD_EN CYREG_PRT3_LCD_EN
#define Pin_2__MASK 0x02u
#define Pin_2__PORT 3
#define Pin_2__PRT CYREG_PRT3_PRT
#define Pin_2__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Pin_2__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Pin_2__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Pin_2__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Pin_2__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Pin_2__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Pin_2__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Pin_2__PS CYREG_PRT3_PS
#define Pin_2__SHIFT 1
#define Pin_2__SLW CYREG_PRT3_SLW

/* Miscellaneous */
/* -- WARNING: define names containting LEOPARD or PANTHER are deprecated and will be removed in a future release */
#define CYDEV_CHIP_REVISION_5A_ES1 1
#define CYDEV_CHIP_REV_PANTHER_ES1 1
#define CYDEV_CHIP_MEMBER_5A 2
#define CYDEV_CHIP_FAMILY_PSOC5 2
#define CYDEV_CHIP_DIE_PANTHER 2
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_DIE_PANTHER
#define autoVrefComparator__CLK CYREG_CMP1_CLK
#define autoVrefComparator__CMP_MASK 0x02u
#define autoVrefComparator__CMP_NUMBER 1
#define autoVrefComparator__CR CYREG_CMP1_CR
#define autoVrefComparator__LUT__CR CYREG_LUT1_CR
#define autoVrefComparator__LUT__MSK CYREG_LUT_MSK
#define autoVrefComparator__LUT__MSK_MASK 0x02u
#define autoVrefComparator__LUT__MSK_SHIFT 1
#define autoVrefComparator__LUT__MX CYREG_LUT1_MX
#define autoVrefComparator__LUT__SR CYREG_LUT_SR
#define autoVrefComparator__LUT__SR_MASK 0x02u
#define autoVrefComparator__LUT__SR_SHIFT 1
#define autoVrefComparator__PM_ACT_CFG CYREG_PM_ACT_CFG7
#define autoVrefComparator__PM_ACT_MSK 0x04u
#define autoVrefComparator__PM_STBY_CFG CYREG_PM_STBY_CFG7
#define autoVrefComparator__PM_STBY_MSK 0x04u
#define autoVrefComparator__SW0 CYREG_CMP1_SW0
#define autoVrefComparator__SW2 CYREG_CMP1_SW2
#define autoVrefComparator__SW3 CYREG_CMP1_SW3
#define autoVrefComparator__SW4 CYREG_CMP1_SW4
#define autoVrefComparator__SW6 CYREG_CMP1_SW6
#define autoVrefComparator__TR CYREG_CMP1_TR
#define autoVrefComparator__TRIM__TR0 CYREG_FLSHID_MFG_CFG_CMP1_TR0
#define autoVrefComparator__TRIM__TR0_HS CYREG_FLSHID_CUST_TABLES_CMP1_TR0_HS
#define autoVrefComparator__WRK CYREG_CMP_WRK
#define autoVrefComparator__WRK_MASK 0x02u
#define autoVrefComparator__WRK_SHIFT 1
#define BCLK__BUS_CLK__HZ 70000000U
#define BCLK__BUS_CLK__KHZ 70000U
#define BCLK__BUS_CLK__MHZ 70U
#define CYDEV_BOOTLOADER_CHECKSUM 0
#define CYDEV_BOOTLOADER_CHECKSUM_BASIC 0
#define CYDEV_BOOTLOADER_CHECKSUM_CRC 1
#define CYDEV_BOOTLOADER_WAIT_COMMAND 1
#define CYDEV_BOOTLOADER_WAIT_TIME 10
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_DIE_LEOPARD 1
#define CYDEV_CHIP_DIE_UNKNOWN 0
#define CYDEV_CHIP_FAMILY_PSOC3 1
#define CYDEV_CHIP_FAMILY_UNKNOWN 0
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC5
#define CYDEV_CHIP_JTAG_ID 0x0E13C069
#define CYDEV_CHIP_MEMBER_3A 1
#define CYDEV_CHIP_MEMBER_UNKNOWN 0
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_5A
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REV_PANTHER_ES1
#define CYDEV_CHIP_REV_LEOPARD_ES1 0
#define CYDEV_CHIP_REV_LEOPARD_ES2 1
#define CYDEV_CHIP_REV_LEOPARD_ES3 3
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3
#define CYDEV_CHIP_REV_PANTHER_ES0 0
#define CYDEV_CHIP_REVISION_3A_ES1 0
#define CYDEV_CHIP_REVISION_3A_ES2 1
#define CYDEV_CHIP_REVISION_3A_ES3 3
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3
#define CYDEV_CHIP_REVISION_5A_ES0 0
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_5A_ES1
#define CYDEV_CONFIG_FORCE_ROUTE 0
#define CYDEV_CONFIG_UNUSED_IO 0
#define CYDEV_CONFIGURATION_COMPRESSED 0
#define CYDEV_CONFIGURATION_DMA 1
#define CYDEV_CONFIGURATION_ECC 1
#define CYDEV_CONFIGURATION_IMOENABLED 1
#define CYDEV_CONFIGURATION_MODE 2
#define CYDEV_DATA_CACHE_ENABLED 1
#define CYDEV_DEBUG_ENABLE_MASK 0x01
#define CYDEV_DEBUG_ENABLE_REGISTER CYREG_MLOGIC_DBG_DBE
#define CYDEV_DEBUGGING_DPS 2
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DEBUGGING_REQXRES 1
#define CYDEV_DEBUGGING_XRES 0
#define CYDEV_ECC_ENABLE 0
#define CYDEV_HEAP_SIZE 4096
#define CYDEV_INSTRUCT_CACHE_ENABLED 1
#define CYDEV_STACK_SIZE 16384
#define CYDEV_USB_CLK_OSC_LOCKING_ENABLED_AT_PWR_UP 
#define CYDEV_VDDA 5.0
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5.0
#define CYDEV_VDDD_MV 5000
#define CYDEV_VDDIO0 5.0
#define CYDEV_VDDIO0_MV 5000
#define CYDEV_VDDIO1 5.0
#define CYDEV_VDDIO1_MV 5000
#define CYDEV_VDDIO2 5.0
#define CYDEV_VDDIO2_MV 5000
#define CYDEV_VDDIO3 5.0
#define CYDEV_VDDIO3_MV 5000
#define CYDEV_VIO0 5
#define CYDEV_VIO0_MV 5000
#define CYDEV_VIO1 5
#define CYDEV_VIO1_MV 5000
#define CYDEV_VIO2 5
#define CYDEV_VIO2_MV 5000
#define CYDEV_VIO3 5
#define CYDEV_VIO3_MV 5000
#define DMA_CHANNELS_USED__MASK0 0x00003304u
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
