/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 1.0 Production
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2010, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <Pin_Col_aliases.h>
#include <Matrix_CR.h>
#include <Pin_Signal_In_A_aliases.h>
#include <DMA_Debug_dma.h>
#include <DMA_ADC_B_dma.h>
#include <ADC_SAR_B.h>
#include <PGA_Stage2_B.h>
#include <PGA_Stage1_B.h>
#include <ADC_SAR_A.h>
#include <Pin_Signal_In_B_aliases.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <DMA_ADC_A_dma.h>
#include <Opamp_Vref.h>
#include <Pin_Vref_aliases.h>
#include <Opamp_A.h>
#include <DMA_Filter_A_dma.h>
#include <VDAC8_0.h>
#include <Filter.h>
#include <Filter_PVT.h>
#include <Pin_Debug_aliases.h>
#include <VDAC8_Debug.h>
#include <Pin_Reserved_aliases.h>
#include <Opamp_Debug.h>
#include <Pin_Row_A_aliases.h>
#include <AMux_Row_A.h>
#include <Pin_Row_B_aliases.h>
#include <Pin_Debug_IRQ_aliases.h>
#include <Pin_Debug_IRQ.h>
#include <ISR_Debug_Slow.h>
#include <ISR_Debug_Fast.h>
#include <Pin_Row_IO_A_aliases.h>
#include <Clock_Signal_Out.h>
#include <PGA_Stage1_A.h>
#include <Pin_Matrix_Switch_ISR_Time_aliases.h>
#include <Pin_Matrix_Switch_ISR_Time.h>
#include <Pin_Opamp_A_out_aliases.h>
#include <Opamp_B.h>
#include <Pin_Opamp_B_out_aliases.h>
#include <Pin_Opamp_A_plus_aliases.h>
#include <Pin_Opamp_B_plus_aliases.h>
#include <DMA_Filter_B_dma.h>
#include <Matrix_SR.h>
#include <Matrix_Channel.h>
#include <PGA_Stage2_A.h>
#include <ISR_Debug_Fast_2.h>
#include <USBUART_FIFO.h>
#include <USBUART.h>
#include <USBUART_API.h>
#include <USBUART_hid.h>
#include <Pin_Soft_Filter_Time_aliases.h>
#include <Pin_Soft_Filter_Time.h>
#include <ISR_Matrix.h>
#include <AMux_Row_B.h>
#include <Pin_Row_IO_B_aliases.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <ADC_SAR_B_theACLK.h>
#include <ADC_SAR_A_theACLK.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
